// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use super::super::context::{LoadContext, SaveContext};

use super::channel_account::ChannelAccount;

use super::conversation_account::ConversationAccount;

/// Bot Framework Activity fields Castia consumes from Teams and Foundry turns.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Activity {
    pub r#type: Option<String>,
    pub id: Option<String>,
    pub text: Option<String>,
    pub service_url: Option<String>,
    pub channel_id: Option<String>,
    pub from: Option<ChannelAccount>,
    pub recipient: Option<ChannelAccount>,
    pub conversation: Option<ConversationAccount>,
    pub reply_to_id: Option<String>,
    pub entities: serde_json::Value,
    pub channel_data: serde_json::Value,
    pub name: Option<String>,
    pub value: Option<serde_json::Value>,
}

impl Activity {
    /// Create a new Activity with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load Activity from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load Activity from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_yaml::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load Activity from an already-parsed JSON value, returning an error
    /// instead of panicking on invalid input. Fallible companion to
    /// `load_from_value` with the same validation policy as `from_json`.
    pub fn try_load_from_value(
        value: &serde_json::Value,
        ctx: &LoadContext,
    ) -> Result<Self, serde_json::Error> {
        Self::validate_input_at(value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(value, ctx))
    }

    /// Load Activity from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        if let Err(message) = Self::validate_input_at(&value, "") {
            panic!("{}", message);
        }
        Self {
            r#type: value.get("type").and_then(|v| v.as_str()).map(|s| s.to_string()),
            id: value.get("id").and_then(|v| v.as_str()).map(|s| s.to_string()),
            text: value.get("text").and_then(|v| v.as_str()).map(|s| s.to_string()),
            service_url: value.get("serviceUrl").and_then(|v| v.as_str()).map(|s| s.to_string()),
            channel_id: value.get("channelId").and_then(|v| v.as_str()).map(|s| s.to_string()),
            from: value.get("from").filter(|v| v.is_object() || v.is_array() || v.is_string()).map(|v| ChannelAccount::load_from_value(v, ctx)),
            recipient: value.get("recipient").filter(|v| v.is_object() || v.is_array() || v.is_string()).map(|v| ChannelAccount::load_from_value(v, ctx)),
            conversation: value.get("conversation").filter(|v| v.is_object() || v.is_array() || v.is_string()).map(|v| ConversationAccount::load_from_value(v, ctx)),
            reply_to_id: value.get("replyToId").and_then(|v| v.as_str()).map(|s| s.to_string()),
            entities: value.get("entities").cloned().unwrap_or(serde_json::Value::Null),
            channel_data: value.get("channelData").cloned().unwrap_or(serde_json::Value::Null),
            name: value.get("name").and_then(|v| v.as_str()).map(|s| s.to_string()),
            value: value.get("value").cloned(),
        }
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        let child_path = if path.is_empty() { "from".to_string() } else { format!("{}.from", path) };
        if let Some(child) = value.get("from") {
            ChannelAccount::validate_input_at(child, &child_path)?;
        }
        let child_path = if path.is_empty() { "recipient".to_string() } else { format!("{}.recipient", path) };
        if let Some(child) = value.get("recipient") {
            ChannelAccount::validate_input_at(child, &child_path)?;
        }
        let child_path = if path.is_empty() { "conversation".to_string() } else { format!("{}.conversation", path) };
        if let Some(child) = value.get("conversation") {
            ConversationAccount::validate_input_at(child, &child_path)?;
        }
        Ok(())
    }

    /// Serialize Activity to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        if let Some(val) = self.r#type.as_ref() {
            result.insert("type".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.id.as_ref() {
            result.insert("id".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.text.as_ref() {
            result.insert("text".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.service_url.as_ref() {
            result.insert("serviceUrl".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.channel_id.as_ref() {
            result.insert("channelId".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.from.as_ref() {
            let nested = val.to_value(ctx);
            if !nested.is_null() {
                result.insert("from".to_string(), nested);
            }
        }
        if let Some(val) = self.recipient.as_ref() {
            let nested = val.to_value(ctx);
            if !nested.is_null() {
                result.insert("recipient".to_string(), nested);
            }
        }
        if let Some(val) = self.conversation.as_ref() {
            let nested = val.to_value(ctx);
            if !nested.is_null() {
                result.insert("conversation".to_string(), nested);
            }
        }
        if let Some(val) = self.reply_to_id.as_ref() {
            result.insert("replyToId".to_string(), serde_json::Value::String(val.clone()));
        }
        if !self.entities.is_null() {
            result.insert("entities".to_string(), self.entities.clone());
        }
        if !self.channel_data.is_null() {
            result.insert("channelData".to_string(), self.channel_data.clone());
        }
        if let Some(val) = self.name.as_ref() {
            result.insert("name".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.value.as_ref() {
            result.insert("value".to_string(), val.clone());
        }
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize Activity to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize Activity to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }
    /// Returns typed reference to the map if the field is an object.
    /// Returns `None` if the field is null or not an object.
    pub fn as_entities_dict(&self) -> Option<&serde_json::Map<String, serde_json::Value>> {
        self.entities.as_object()
    }

    /// Returns typed reference to the map if the field is an object.
    /// Returns `None` if the field is null or not an object.
    pub fn as_channel_data_dict(&self) -> Option<&serde_json::Map<String, serde_json::Value>> {
        self.channel_data.as_object()
    }

}

// Serde for `Activity` delegates to the canonical to_value/load_from_value
// logic so its serde wire form always equals the canonical to_value/load_from_value form. Uses a default (no-op) context — no ${env:}/${file:}
// resolution here — leaving the context-aware LoadContext/SaveContext API intact.
#[cfg(feature = "serde")]
impl serde::Serialize for Activity {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde::Serialize::serialize(&self.to_value(&SaveContext::default()), serializer)
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for Activity {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        Self::validate_input_at(&value, "").map_err(serde::de::Error::custom)?;
        Ok(Self::load_from_value(&value, &LoadContext::default()))
    }
}
