// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use super::super::context::{LoadContext, SaveContext};

/// A user, agent, or app instance on an Activity channel.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct ChannelAccount {
    pub id: Option<String>,
    pub name: Option<String>,
    pub aad_object_id: Option<String>,
    pub role: Option<String>,
    pub agentic_user_id: Option<String>,
    pub agentic_app_id: Option<String>,
    pub tenant_id: Option<String>,
}

impl ChannelAccount {
    /// Create a new ChannelAccount with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load ChannelAccount from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load ChannelAccount from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_yaml::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load ChannelAccount from an already-parsed JSON value, returning an error
    /// instead of panicking on invalid input. Fallible companion to
    /// `load_from_value` with the same validation policy as `from_json`.
    pub fn try_load_from_value(
        value: &serde_json::Value,
        ctx: &LoadContext,
    ) -> Result<Self, serde_json::Error> {
        Self::validate_input_at(value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(value, ctx))
    }

    /// Load ChannelAccount from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        if let Err(message) = Self::validate_input_at(&value, "") {
            panic!("{}", message);
        }
        Self {
            id: value.get("id").and_then(|v| v.as_str()).map(|s| s.to_string()),
            name: value.get("name").and_then(|v| v.as_str()).map(|s| s.to_string()),
            aad_object_id: value.get("aadObjectId").and_then(|v| v.as_str()).map(|s| s.to_string()),
            role: value.get("role").and_then(|v| v.as_str()).map(|s| s.to_string()),
            agentic_user_id: value.get("agenticUserId").and_then(|v| v.as_str()).map(|s| s.to_string()),
            agentic_app_id: value.get("agenticAppId").and_then(|v| v.as_str()).map(|s| s.to_string()),
            tenant_id: value.get("tenantId").and_then(|v| v.as_str()).map(|s| s.to_string()),
        }
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        Ok(())
    }

    /// Serialize ChannelAccount to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        if let Some(val) = self.id.as_ref() {
            result.insert("id".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.name.as_ref() {
            result.insert("name".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.aad_object_id.as_ref() {
            result.insert("aadObjectId".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.role.as_ref() {
            result.insert("role".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.agentic_user_id.as_ref() {
            result.insert("agenticUserId".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.agentic_app_id.as_ref() {
            result.insert("agenticAppId".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.tenant_id.as_ref() {
            result.insert("tenantId".to_string(), serde_json::Value::String(val.clone()));
        }
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize ChannelAccount to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize ChannelAccount to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }
}

// Serde for `ChannelAccount` delegates to the canonical to_value/load_from_value
// logic so its serde wire form always equals the canonical to_value/load_from_value form. Uses a default (no-op) context — no ${env:}/${file:}
// resolution here — leaving the context-aware LoadContext/SaveContext API intact.
#[cfg(feature = "serde")]
impl serde::Serialize for ChannelAccount {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde::Serialize::serialize(&self.to_value(&SaveContext::default()), serializer)
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for ChannelAccount {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        Self::validate_input_at(&value, "").map_err(serde::de::Error::custom)?;
        Ok(Self::load_from_value(&value, &LoadContext::default()))
    }
}
