// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use super::super::context::{LoadContext, SaveContext};

use super::channel_account::ChannelAccount;

/// A mention entity embedded in an Activity.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Mention {
    pub r#type: Option<String>,
    pub mentioned: Option<ChannelAccount>,
    pub text: Option<String>,
}

impl Mention {
    /// Create a new Mention with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load Mention from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load Mention from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_yaml::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load Mention from an already-parsed JSON value, returning an error
    /// instead of panicking on invalid input. Fallible companion to
    /// `load_from_value` with the same validation policy as `from_json`.
    pub fn try_load_from_value(
        value: &serde_json::Value,
        ctx: &LoadContext,
    ) -> Result<Self, serde_json::Error> {
        Self::validate_input_at(value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(value, ctx))
    }

    /// Load Mention from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        if let Err(message) = Self::validate_input_at(&value, "") {
            panic!("{}", message);
        }
        Self {
            r#type: value.get("type").and_then(|v| v.as_str()).map(|s| s.to_string()),
            mentioned: value.get("mentioned").filter(|v| v.is_object() || v.is_array() || v.is_string()).map(|v| ChannelAccount::load_from_value(v, ctx)),
            text: value.get("text").and_then(|v| v.as_str()).map(|s| s.to_string()),
        }
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        let child_path = if path.is_empty() { "mentioned".to_string() } else { format!("{}.mentioned", path) };
        if let Some(child) = value.get("mentioned") {
            ChannelAccount::validate_input_at(child, &child_path)?;
        }
        Ok(())
    }

    /// Serialize Mention to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        if let Some(val) = self.r#type.as_ref() {
            result.insert("type".to_string(), serde_json::Value::String(val.clone()));
        }
        if let Some(val) = self.mentioned.as_ref() {
            let nested = val.to_value(ctx);
            if !nested.is_null() {
                result.insert("mentioned".to_string(), nested);
            }
        }
        if let Some(val) = self.text.as_ref() {
            result.insert("text".to_string(), serde_json::Value::String(val.clone()));
        }
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize Mention to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize Mention to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }
}

// Serde for `Mention` delegates to the canonical to_value/load_from_value
// logic so its serde wire form always equals the canonical to_value/load_from_value form. Uses a default (no-op) context — no ${env:}/${file:}
// resolution here — leaving the context-aware LoadContext/SaveContext API intact.
#[cfg(feature = "serde")]
impl serde::Serialize for Mention {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde::Serialize::serialize(&self.to_value(&SaveContext::default()), serializer)
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for Mention {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        Self::validate_input_at(&value, "").map_err(serde::de::Error::custom)?;
        Ok(Self::load_from_value(&value, &LoadContext::default()))
    }
}
