// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

use super::protocols::activity::Activity;

use super::protocols::mention::Mention;

/// Portable semantic helpers every Activity runtime must provide.
#[async_trait::async_trait]
pub trait ActivityRuntime: Send + Sync {
    /// Return recipient.agenticAppId when the Activity is agentic.
    fn agentic_instance_id(&self, activity: &Activity) -> Option<String>;
    /// Return the agentic tenant id from recipient first, then conversation.
    fn agentic_tenant_id(&self, activity: &Activity) -> Option<String>;
    /// Return recipient.agenticUserId when the Activity is agentic.
    fn agentic_user(&self, activity: &Activity) -> Option<String>;
    /// Return the channel id without any channel-specific suffix.
    fn channel(&self, activity: &Activity) -> Option<String>;
    /// Whether the Activity recipient represents a Foundry agentic identity.
    fn is_agentic_request(&self, activity: &Activity) -> bool;
    /// Return only mention entities from an Activity payload.
    fn mentions(&self, activity: &Activity) -> Vec<Mention>;
}
