// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

use std::sync::atomic::AtomicBool as CancellationToken;

use super::optimizing::agent_config_resolution::AgentConfigResolution;

/// Portable optimizer config resolver seam; source precedence is pinned by conformance fixtures.
#[async_trait::async_trait]
pub trait AgentConfigResolver: Send + Sync {
    /// Resolve the active agent config from injected candidate, resolver API, local baseline, or defaults.
    async fn resolve(
        &self,
        config_dir: &Option<String>,
        cancellation: &CancellationToken,
    ) -> Result<AgentConfigResolution, Box<dyn std::error::Error + Send + Sync>>;
}
