// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure preflight diagnostic/report shaping. Filesystem import and Python execution stay host-specific.
#[async_trait::async_trait]
pub trait BuildPreflightRuntime: Send + Sync {
    fn deployment_context_diagnostics(
        &self,
        environment: &serde_json::Value,
        deployment: &bool,
    ) -> serde_json::Value;
    fn preflight_report(
        &self,
        root: &String,
        app_target: &String,
        protocols: &Vec<String>,
        diagnostics: &serde_json::Value,
    ) -> serde_json::Value;
    fn required_env_diagnostics(
        &self,
        environment: &serde_json::Value,
        required_env: &Vec<String>,
    ) -> serde_json::Value;
}
