// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Offline project scaffold file map and identifier validation.
#[async_trait::async_trait]
pub trait BuildScaffoldRuntime: Send + Sync {
    fn scaffold_files(&self, name: &String, model: &String) -> serde_json::Value;
}
