// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Offline project-test timeout validation and report classification.
#[async_trait::async_trait]
pub trait BuildTestingRuntime: Send + Sync {
    fn project_test_report(
        &self,
        root: &String,
        exit_code: &i32,
        output: &String,
        timed_out: &bool,
    ) -> serde_json::Value;
    fn validate_test_timeout(&self, timeout: &f64) -> f64;
}
