// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure Teams card and action builders used by outgoing message payloads.
#[async_trait::async_trait]
pub trait CardsRuntime: Send + Sync {
    fn action_chips(&self, actions: &serde_json::Value, prompt: &String) -> serde_json::Value;
    fn adaptive_card(
        &self,
        body: &serde_json::Value,
        card: &serde_json::Value,
    ) -> serde_json::Value;
    fn decision_card(
        &self,
        actions: &serde_json::Value,
        prompt: &String,
        card: &serde_json::Value,
    ) -> serde_json::Value;
    fn suggested_actions(&self, actions: &serde_json::Value) -> serde_json::Value;
}
