// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use super::context::{LoadContext, SaveContext};

use super::protocols::activity::Activity;

use super::optimizing::agent_config_resolution::AgentConfigResolution;

/// Aggregate root for Castia's generated cross-runtime contract surface.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct CastiaContracts {
    pub activity: Activity,
    pub agent_config_resolution: AgentConfigResolution,
}

impl CastiaContracts {
    /// Create a new CastiaContracts with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Load CastiaContracts from a JSON string.
    pub fn from_json(json: &str, ctx: &LoadContext) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_str(json)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load CastiaContracts from a YAML string.
    pub fn from_yaml(yaml: &str, ctx: &LoadContext) -> Result<Self, serde_yaml::Error> {
        let value: serde_json::Value = serde_yaml::from_str(yaml)?;
        Self::validate_input_at(&value, "")
            .map_err(|message| <serde_yaml::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(&value, ctx))
    }

    /// Load CastiaContracts from an already-parsed JSON value, returning an error
    /// instead of panicking on invalid input. Fallible companion to
    /// `load_from_value` with the same validation policy as `from_json`.
    pub fn try_load_from_value(
        value: &serde_json::Value,
        ctx: &LoadContext,
    ) -> Result<Self, serde_json::Error> {
        Self::validate_input_at(value, "")
            .map_err(|message| <serde_json::Error as serde::de::Error>::custom(message))?;
        Ok(Self::load_from_value(value, ctx))
    }

    /// Load CastiaContracts from a `serde_json::Value`.
    ///
    /// Calls `ctx.process_input` before field extraction.
    pub fn load_from_value(value: &serde_json::Value, ctx: &LoadContext) -> Self {
        let value = ctx.process_input(value.clone());
        if let Err(message) = Self::validate_input_at(&value, "") {
            panic!("{}", message);
        }
        Self {
            activity: value.get("activity").filter(|v| v.is_object() || v.is_array() || v.is_string()).map(|v| Activity::load_from_value(v, ctx)).unwrap_or_default(),
            agent_config_resolution: value.get("agentConfigResolution").filter(|v| v.is_object() || v.is_array() || v.is_string()).map(|v| AgentConfigResolution::load_from_value(v, ctx)).unwrap_or_default(),
        }
    }

    pub(crate) fn validate_input_at(value: &serde_json::Value, path: &str) -> Result<(), String> {
        let child_path = if path.is_empty() { "activity".to_string() } else { format!("{}.activity", path) };
        let child = value.get("activity").filter(|candidate| !candidate.is_null())
            .ok_or_else(|| format!("{}: missing required field", child_path))?;
        Activity::validate_input_at(child, &child_path)?;
        let child_path = if path.is_empty() { "agentConfigResolution".to_string() } else { format!("{}.agentConfigResolution", path) };
        let child = value.get("agentConfigResolution").filter(|candidate| !candidate.is_null())
            .ok_or_else(|| format!("{}: missing required field", child_path))?;
        AgentConfigResolution::validate_input_at(child, &child_path)?;
        Ok(())
    }

    /// Serialize CastiaContracts to a `serde_json::Value`.
    ///
    /// Calls `ctx.process_dict` after serialization.
    pub fn to_value(&self, ctx: &SaveContext) -> serde_json::Value {
        let mut result = serde_json::Map::new();
        // Write base fields
        {
            let nested = self.activity.to_value(ctx);
            result.insert("activity".to_string(), nested);
        }
        {
            let nested = self.agent_config_resolution.to_value(ctx);
            result.insert("agentConfigResolution".to_string(), nested);
        }
        ctx.process_dict(serde_json::Value::Object(result))
    }

    /// Serialize CastiaContracts to a JSON string.
    pub fn to_json(&self, ctx: &SaveContext) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.to_value(ctx))
    }

    /// Serialize CastiaContracts to a YAML string.
    pub fn to_yaml(&self, ctx: &SaveContext) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(&self.to_value(ctx))
    }
}

// Serde for `CastiaContracts` delegates to the canonical to_value/load_from_value
// logic so its serde wire form always equals the canonical to_value/load_from_value form. Uses a default (no-op) context — no ${env:}/${file:}
// resolution here — leaving the context-aware LoadContext/SaveContext API intact.
#[cfg(feature = "serde")]
impl serde::Serialize for CastiaContracts {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serde::Serialize::serialize(&self.to_value(&SaveContext::default()), serializer)
    }
}

#[cfg(feature = "serde")]
impl<'de> serde::Deserialize<'de> for CastiaContracts {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        Self::validate_input_at(&value, "").map_err(serde::de::Error::custom)?;
        Ok(Self::load_from_value(&value, &LoadContext::default()))
    }
}
