// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]


/// Portable helper seam for the OpenAI Chat Completions protocol wire shape.
#[async_trait::async_trait]
pub trait ChatRuntime: Send + Sync {
    /// Wrap handler text in a minimal OpenAI Chat Completions envelope; vector comparison normalizes the generated id.
    fn body(&self, text: &String) -> serde_json::Value;
    /// Return the content of the last user message in a Chat Completions messages array.
    fn last_user_text(&self, messages: &serde_json::Value) -> String;
}
