// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

use super::protocols::activity::Activity;

/// Pure Bot Framework connector request builders. HTTP and authorization stay outside the seam.
#[async_trait::async_trait]
pub trait ConnectorRuntime: Send + Sync {
    fn connector_endpoint(&self, activity: &Activity) -> serde_json::Value;
    fn connector_envelope(&self, activity: &Activity) -> serde_json::Value;
    fn connector_ok(&self, response: &serde_json::Value) -> bool;
    fn created_activity_id(&self, response: &serde_json::Value) -> Option<String>;
    fn delete_activity_request(
        &self,
        activity: &Activity,
        activity_id: &String,
    ) -> serde_json::Value;
    fn post_activity_request(
        &self,
        activity: &Activity,
        payload: &serde_json::Value,
    ) -> serde_json::Value;
    fn reaction_request(
        &self,
        activity: &Activity,
        reaction_type: &String,
        method: &String,
    ) -> serde_json::Value;
    fn typing_request(&self, activity: &Activity) -> serde_json::Value;
    fn update_activity_request(
        &self,
        activity: &Activity,
        activity_id: &String,
        payload: &serde_json::Value,
    ) -> serde_json::Value;
}
