// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure azure.yaml protocol reconciliation helpers. YAML loading/writing and app importing stay host-specific.
#[async_trait::async_trait]
pub trait DeliveryManifestRuntime: Send + Sync {
    fn plan_manifest(
        &self,
        app_name: &String,
        registered_protocols: &Vec<String>,
        manifest: &serde_json::Value,
        check: &bool,
    ) -> serde_json::Value;
    fn publishable_protocols(&self, registered_protocols: &Vec<String>) -> Vec<String>;
    fn service_protocol_items(&self, protocols: &Vec<String>) -> serde_json::Value;
    fn skipped_protocols(&self, registered_protocols: &Vec<String>) -> Vec<String>;
}
