// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure azd deployment validation helpers. Shell execution and manifest IO remain host-specific.
#[async_trait::async_trait]
pub trait DeliveryAzdRuntime: Send + Sync {
    fn command_error_message(
        &self,
        command: &Vec<String>,
        return_code: &i32,
        stdout: &String,
        stderr: &String,
    ) -> String;
    fn validate_deployment_input(
        &self,
        service: &String,
        environment: &Option<String>,
        project_endpoint: &String,
        project_resource_id: &String,
        timeout: &f64,
    ) -> serde_json::Value;
    fn validate_environment_values(
        &self,
        values: &serde_json::Value,
        requested_environment: &Option<String>,
        project_endpoint: &String,
        project_resource_id: &String,
        subscription_id: &String,
    ) -> serde_json::Value;
    fn verify_payload(
        &self,
        payload: &serde_json::Value,
        service: &String,
        project_endpoint: &String,
        project_resource_id: &String,
        expected_model: &Option<String>,
        expected_candidate: &Option<String>,
        expected_version: &Option<String>,
    ) -> serde_json::Value;
}
