// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure Teams message decoration builders.
#[async_trait::async_trait]
pub trait EntitiesRuntime: Send + Sync {
    fn citation(
        &self,
        position: &i32,
        name: &String,
        url: &String,
        abstract_text: &String,
        keywords: &serde_json::Value,
        icon: &String,
    ) -> serde_json::Value;
    fn feedback_channel_data(&self, kind: &String) -> serde_json::Value;
    fn mention_entity(&self, account_id: &String, name: &String) -> serde_json::Value;
    fn message_entity(
        &self,
        ai_generated: &bool,
        citations: &serde_json::Value,
        sensitivity: &serde_json::Value,
    ) -> serde_json::Value;
    fn sensitivity_label(&self, name: &String, description: &String) -> serde_json::Value;
}
