// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure fine-tuning validators and payload builders. Uploads and job submissions are intentionally out of scope.
#[async_trait::async_trait]
pub trait FinetuningTrainingRuntime: Send + Sync {
    fn build_dpo_method(&self, hyperparameters: &serde_json::Value) -> serde_json::Value;
    fn build_rft_job(
        &self,
        model: &String,
        training_file: &String,
        validation_file: &String,
        grader: &serde_json::Value,
        hyperparameters: &serde_json::Value,
        response_format: &serde_json::Value,
        suffix: &Option<String>,
        seed: &Option<i32>,
    ) -> serde_json::Value;
    fn build_rft_method(
        &self,
        grader: &serde_json::Value,
        hyperparameters: &serde_json::Value,
        response_format: &serde_json::Value,
    ) -> serde_json::Value;
    fn build_sft_job(
        &self,
        model: &String,
        training_file: &String,
        validation_file: &Option<String>,
        hyperparameters: &serde_json::Value,
        suffix: &Option<String>,
        seed: &Option<i32>,
    ) -> serde_json::Value;
    fn build_sft_method(&self, hyperparameters: &serde_json::Value) -> serde_json::Value;
    fn string_check_grader(
        &self,
        name: &String,
        input: &String,
        reference: &String,
        operation: &String,
    ) -> serde_json::Value;
    fn validate_dpo_example(&self, row: &serde_json::Value) -> Vec<String>;
    fn validate_grader(&self, grader: &serde_json::Value) -> Vec<String>;
    fn validate_rft_dataset(
        &self,
        rows: &serde_json::Value,
        grader: &serde_json::Value,
        split: &String,
    ) -> Vec<String>;
    fn validate_rft_example(&self, row: &serde_json::Value) -> Vec<String>;
    fn validate_sft_example(&self, row: &serde_json::Value) -> Vec<String>;
}
