// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure fine-tuning job management guards. These seams never upload files, submit training, or deploy models.
#[async_trait::async_trait]
pub trait FinetuningJobsRuntime: Send + Sync {
    fn deployment_handoff(
        &self,
        project_endpoint: &Option<String>,
        job: &serde_json::Value,
    ) -> serde_json::Value;
    fn download_guard(
        &self,
        job: &serde_json::Value,
        file_id: &String,
        max_bytes: &serde_json::Value,
    ) -> serde_json::Value;
    fn download_limit_exceeded(
        &self,
        written: &serde_json::Value,
        max_bytes: &serde_json::Value,
    ) -> bool;
    fn job_page_request(
        &self,
        job_id: &String,
        limit: &serde_json::Value,
        after: &Option<String>,
    ) -> serde_json::Value;
    fn job_reference(
        &self,
        project_endpoint: &String,
        job_id: &String,
        schema_version: &i32,
    ) -> serde_json::Value;
    fn page_request(&self, limit: &serde_json::Value, after: &Option<String>) -> serde_json::Value;
    fn page_slice(&self, data: &serde_json::Value, limit: &serde_json::Value) -> serde_json::Value;
    fn parse_job_reference(&self, data: &serde_json::Value) -> serde_json::Value;
    fn result_files(&self, job: &serde_json::Value) -> Vec<String>;
    fn status_request(
        &self,
        job_id: &String,
        request_timeout: &f64,
        timeout: &Option<f64>,
    ) -> serde_json::Value;
    fn terminal_status(&self, status: &String) -> bool;
    fn validate_request_timeout(&self, request_timeout: &f64) -> serde_json::Value;
    fn watch_poll_timeout(&self, request_timeout: &f64, remaining: &f64) -> serde_json::Value;
    fn watch_request(
        &self,
        job_id: &String,
        timeout: &f64,
        poll_interval: &f64,
    ) -> serde_json::Value;
    fn watch_sleep_duration(&self, poll_interval: &f64, remaining: &f64) -> serde_json::Value;
}
