// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure hosting credential helpers. Managed identity acquisition and HTTP POSTs stay host-specific.
#[async_trait::async_trait]
pub trait HostingCredentialsRuntime: Send + Sync {
    fn agentic_identity_from_env(&self, env: &serde_json::Value) -> serde_json::Value;
    fn bearer(&self, token: &String) -> String;
    fn bot_connector_credential(&self, env: &serde_json::Value) -> serde_json::Value;
    fn hosting_scopes(&self) -> serde_json::Value;
    fn instance_token_request(
        &self,
        instance_client_id: &String,
        agent_assertion: &String,
    ) -> serde_json::Value;
    fn is_local_run(&self, env: &serde_json::Value) -> bool;
    fn tenant_token_endpoint(&self, tenant_id: &String) -> String;
    fn token_response_access_token(
        &self,
        status: &i32,
        body: &serde_json::Value,
        text: &String,
    ) -> String;
    fn user_fic_token_request(
        &self,
        instance_client_id: &String,
        agent_assertion: &String,
        instance_token: &String,
        agentic_user_id: &String,
        scope: &String,
    ) -> serde_json::Value;
}
