// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure hosting server helpers. FastAPI route registration and network serving remain host-specific.
#[async_trait::async_trait]
pub trait HostingServerRuntime: Send + Sync {
    fn readiness_body(&self) -> String;
    fn sse_event(&self, event_type: &String, payload: &serde_json::Value) -> String;
    fn wire_endpoints(&self, wire_protocols: &Vec<String>) -> serde_json::Value;
}
