// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Hosted-vs-local run detection. Environment collection stays host-specific.
#[async_trait::async_trait]
pub trait HostingAuthRuntime: Send + Sync {
    fn local_run(&self, env: &serde_json::Value) -> bool;
}
