// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

use super::protocols::activity::Activity;

/// Agentic-user mailbox identity gates.
#[async_trait::async_trait]
pub trait IdentityRuntime: Send + Sync {
    fn agentic_user_id(&self, activity: &Activity) -> Option<String>;
    fn require_agentic_user(&self, activity: &Activity) -> String;
}
