// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure Microsoft Graph integration helper contracts. Token minting and HTTP execution remain host-specific.
#[async_trait::async_trait]
pub trait IntegrationsGraphRuntime: Send + Sync {
    fn drive_share_invite_payload(&self, requester_object_id: &String) -> serde_json::Value;
    fn drive_share_result(
        &self,
        item_id: &String,
        requester_object_id: &String,
        status: &i32,
        detail: &String,
    ) -> serde_json::Value;
    fn drive_upload_result(
        &self,
        status: &i32,
        granted_scopes: &String,
        web_url: &String,
        shared: &serde_json::Value,
        detail: &String,
    ) -> serde_json::Value;
    fn drive_upload_url(&self, path: &String) -> String;
    fn mailbox_messages_url(&self, top: &i32, unread_only: &bool) -> String;
    fn reply_mail_request(&self, message_id: &String, body: &String) -> serde_json::Value;
    fn reply_mail_result(
        &self,
        status: &i32,
        granted_scopes: &String,
        detail: &String,
    ) -> serde_json::Value;
    fn send_mail_payload(&self, to: &String, subject: &String, body: &String) -> serde_json::Value;
    fn send_mail_result(
        &self,
        status: &i32,
        granted_scopes: &String,
        detail: &String,
    ) -> serde_json::Value;
    fn summarize_mailbox_message(&self, message: &serde_json::Value) -> serde_json::Value;
}
