// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure Foundry Toolbox MCP helper contracts. Token minting stays host-specific.
#[async_trait::async_trait]
pub trait IntegrationsToolboxRuntime: Send + Sync {
    fn compose_toolbox_endpoint(
        &self,
        project_endpoint: &String,
        name: &String,
        version: &Option<String>,
    ) -> String;
    fn knowledge_base_mcp_tool(&self, config: &serde_json::Value) -> serde_json::Value;
    fn platform_endpoint_env(&self, name: &String) -> String;
    fn resolve_toolbox_endpoint(&self, env: &serde_json::Value) -> Option<String>;
    fn toolbox_mcp_tool(&self, config: &serde_json::Value) -> serde_json::Value;
}
