// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]


/// Portable helper seam for the Foundry Invocations protocol wire shape.
#[async_trait::async_trait]
pub trait InvocationsRuntime: Send + Sync {
    /// Wrap handler text in Castia's minimal Invocations output envelope.
    fn body(&self, text: &String) -> serde_json::Value;
    /// Normalize an Invocations request payload to the text sent to a handler.
    fn input_text(&self, body: &serde_json::Value) -> String;
}
