// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

use super::protocols::activity::Activity;

/// Activity invoke request/response helpers.
#[async_trait::async_trait]
pub trait InvokesRuntime: Send + Sync {
    fn card_action(&self, activity: &Activity) -> serde_json::Value;
    fn card_invoke_response(&self, card: &serde_json::Value) -> serde_json::Value;
    fn feedback_payload(&self, activity: &Activity) -> serde_json::Value;
    fn message_invoke_response(&self, text: &String) -> serde_json::Value;
}
