// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// File-backed immutable lifecycle artifact store contract.
#[async_trait::async_trait]
pub trait LifecycleStorageRuntime: Send + Sync {
    fn get_artifact(&self, root: &String, id: &String) -> serde_json::Value;
    fn put_artifact(&self, root: &String, record: &serde_json::Value) -> String;
}
