// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Portable lifecycle evidence record primitives.
#[async_trait::async_trait]
pub trait LifecycleRecordsRuntime: Send + Sync {
    fn canonical_json(&self, value: &serde_json::Value) -> String;
    fn check_public(&self, value: &serde_json::Value) -> bool;
    fn content_hash(&self, value: &serde_json::Value) -> String;
    fn safe_path(&self, path: &String) -> String;
}
