// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Offline lifecycle acceptance gate and run comparison contract.
#[async_trait::async_trait]
pub trait LifecycleAcceptanceRuntime: Send + Sync {
    fn compare_runs(
        &self,
        baseline: &serde_json::Value,
        candidate: &serde_json::Value,
        gate: &serde_json::Value,
    ) -> serde_json::Value;
    fn default_gate(&self) -> serde_json::Value;
}
