// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Offline reviewed lifecycle curation and dataset export contract.
#[async_trait::async_trait]
pub trait LifecycleOperationsRuntime: Send + Sync {
    fn curate_dataset(
        &self,
        traces: &serde_json::Value,
        redaction_version: &String,
        heldout_fraction: &f64,
        seed: &String,
    ) -> serde_json::Value;
    fn dataset_jsonl(&self, dataset: &serde_json::Value, split: &String) -> String;
    async fn evaluate_outcomes(
        &self,
        agent: &serde_json::Value,
        dataset: &serde_json::Value,
        evaluator: &serde_json::Value,
        outcomes: &serde_json::Value,
        split: &String,
        repeats: &i32,
        concurrency: &i32,
        timeout_seconds: &f64,
    ) -> Result<serde_json::Value, Box<dyn std::error::Error + Send + Sync>>;
}
