// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure model-call helper semantics shared by SDKs.
#[async_trait::async_trait]
pub trait ModelRuntime: Send + Sync {
    fn instructions_param(&self, instructions: &Option<String>) -> serde_json::Value;
    fn public_tool_spec(
        &self,
        spec: &serde_json::Value,
        tool_definitions: &serde_json::Value,
    ) -> serde_json::Value;
    fn reasoning_param(&self, effort: &Option<String>) -> serde_json::Value;
}
