// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure live-observe configuration guards and response classifiers; no network submission.
#[async_trait::async_trait]
pub trait ObserveLiveRuntime: Send + Sync {
    fn candidate_config(&self, payload: &serde_json::Value) -> serde_json::Value;
    fn optimizer_status(
        &self,
        payload: &serde_json::Value,
        expected_id: &Option<String>,
    ) -> serde_json::Value;
    fn response_text_result(
        &self,
        response: &serde_json::Value,
        expected: &Option<String>,
    ) -> serde_json::Value;
    fn stream_result(&self, events: &serde_json::Value) -> serde_json::Value;
    fn validate_limits(&self, limits: &serde_json::Value) -> serde_json::Value;
    fn validate_live_config(&self, config: &serde_json::Value) -> serde_json::Value;
}
