// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Offline telemetry query, error-classification, and trace-ingestion verification helpers.
#[async_trait::async_trait]
pub trait ObserveTelemetryRuntime: Send + Sync {
    fn http_error(&self, status: &i32) -> serde_json::Value;
    fn telemetry_probe_plan(
        &self,
        query: &serde_json::Value,
        ingestion_status: &String,
        ingestion_diagnostic: &String,
        ingestion_evidence: &serde_json::Value,
    ) -> serde_json::Value;
    fn trace_query_kql(&self, query: &serde_json::Value) -> serde_json::Value;
    fn verify_probe(
        &self,
        attempts: &serde_json::Value,
        probe_tag: &String,
        timeout_seconds: &f64,
        poll_seconds: &f64,
        max_attempts: &i32,
    ) -> serde_json::Value;
}
