// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Content-minimizing execution record normalization and summary contract.
#[async_trait::async_trait]
pub trait ObserveRecordsRuntime: Send + Sync {
    fn normalize_record(
        &self,
        row: &serde_json::Value,
        include_content: &bool,
    ) -> serde_json::Value;
    fn summarize(&self, records: &serde_json::Value) -> serde_json::Value;
}
