// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure observe feature-suite validation, execution-plan, and drift comparison contract.
#[async_trait::async_trait]
pub trait ObserveSuiteRuntime: Send + Sync {
    fn compare_reports(
        &self,
        current: &serde_json::Value,
        baseline: &serde_json::Value,
    ) -> serde_json::Value;
    fn feature_catalog(&self) -> serde_json::Value;
    fn run_suite(
        &self,
        suite: &serde_json::Value,
        probes: &serde_json::Value,
        prerequisites: &serde_json::Value,
        baseline: &serde_json::Value,
        generated_at: &String,
    ) -> serde_json::Value;
    fn validate_suite(&self, suite: &serde_json::Value) -> serde_json::Value;
}
