// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Foundry GenAI span label attributes used by observe tracing helpers.
#[async_trait::async_trait]
pub trait ObserveTracingRuntime: Send + Sync {
    fn execute_tool_span(&self, name: &String, system: &Option<String>) -> serde_json::Value;
    fn invoke_agent_span(
        &self,
        name: &Option<String>,
        env_name: &Option<String>,
        env_version: &Option<String>,
        system: &Option<String>,
    ) -> serde_json::Value;
}
