// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure Agent Optimizer job helpers. Network submission, polling, and disk writes stay host-specific.
#[async_trait::async_trait]
pub trait OptimizerJobsRuntime: Send + Sync {
    fn best_optimizer_candidate_id(&self, status: &serde_json::Value) -> Option<String>;
    fn optimizer_candidate_apply_plan(
        &self,
        candidate_id: &String,
        config: &serde_json::Value,
    ) -> serde_json::Value;
    fn optimizer_job_id(&self, payload: &serde_json::Value) -> Option<String>;
    fn optimizer_request(
        &self,
        eval_config: &serde_json::Value,
        baseline: &serde_json::Value,
        dataset_items: &serde_json::Value,
        validation_items: &serde_json::Value,
        agent_name: &Option<String>,
        agent_version: &Option<String>,
        eval_model: &Option<String>,
        optimize_model: &Option<String>,
        max_candidates: &Option<i32>,
    ) -> serde_json::Value;
    fn optimizer_rest_request(
        &self,
        project_endpoint: &String,
        action: &String,
        job_id: &Option<String>,
        candidate_id: &Option<String>,
        body: &serde_json::Value,
    ) -> serde_json::Value;
    fn terminal_optimizer_status(&self, status: &Option<String>) -> bool;
}
