// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Portable helper seam for the OpenAI Responses protocol wire shape.
#[async_trait::async_trait]
pub trait ResponsesRuntime: Send + Sync {
    /// Normalize the Responses API polymorphic input field to the text sent to a handler.
    fn input_text(&self, value: &serde_json::Value) -> String;
    /// Wrap handler text in the minimal OpenAI Responses envelope; vector comparison normalizes the generated id.
    fn output_body(&self, text: &String) -> serde_json::Value;
}
