// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

use super::protocols::activity::Activity;

/// Pure Teams surface predicates for Activity routing.
#[async_trait::async_trait]
pub trait RoutingRuntime: Send + Sync {
    fn teams_direct_message(&self, activity: &Activity) -> bool;
    fn teams_group_chat_message(&self, activity: &Activity) -> bool;
    fn teams_tagged_channel_message(&self, activity: &Activity) -> bool;
}
