// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure dispatch planning and result shaping. Calling user code, telemetry, and async dependency execution stay host-specific.
#[async_trait::async_trait]
pub trait RuntimeDispatchRuntime: Send + Sync {
    fn activity_dispatch_plan(
        &self,
        parameters: &serde_json::Value,
        text: &String,
    ) -> serde_json::Value;
    fn activity_result_text(&self, result: &serde_json::Value) -> Option<String>;
    fn invoke_dispatch_plan(
        &self,
        parameters: &serde_json::Value,
        value: &serde_json::Value,
    ) -> serde_json::Value;
    fn invoke_result_body(&self, result: &serde_json::Value) -> serde_json::Value;
    fn return_body(&self, result: &serde_json::Value) -> String;
    fn stream_chunks(&self, result: &serde_json::Value) -> Vec<String>;
    fn wire_dispatch_plan(
        &self,
        handler_name: &String,
        parameters: &serde_json::Value,
        text: &String,
        streaming: &bool,
    ) -> serde_json::Value;
}
