// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure turn decoration helpers. Ambient contextvars and connector IO remain host-specific.
#[async_trait::async_trait]
pub trait RuntimeContextRuntime: Send + Sync {
    fn decorate_message(
        &self,
        payload: &serde_json::Value,
        turn: &serde_json::Value,
        ai_generated: &bool,
        citations: &serde_json::Value,
        sensitivity: &serde_json::Value,
        feedback: &Option<String>,
        importance: &Option<String>,
    ) -> serde_json::Value;
    fn turn_cite(
        &self,
        citations: &serde_json::Value,
        name: &String,
        url: &String,
        abstract_text: &String,
        keywords: &serde_json::Value,
        icon: &String,
    ) -> serde_json::Value;
}
