// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure router registration helpers. Handler decorators and dispatch execution stay host-specific.
#[async_trait::async_trait]
pub trait RuntimeRouterRuntime: Send + Sync {
    fn include_plan(
        &self,
        existing_wire: &Vec<String>,
        incoming_wire: &Vec<String>,
        existing_invokes: &Vec<String>,
        incoming_invokes: &Vec<String>,
    ) -> serde_json::Value;
    fn registered_protocols(
        &self,
        activity_route_count: &i32,
        invoke_names: &Vec<String>,
        wire_protocols: &Vec<String>,
    ) -> Vec<String>;
    fn responses_only_projection(
        &self,
        name: &String,
        has_responses: &bool,
        tool_names: &Vec<String>,
    ) -> serde_json::Value;
}
