// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure Agent/Router application helpers. Decorator registration and handler invocation stay host-specific.
#[async_trait::async_trait]
pub trait RuntimeApplicationRuntime: Send + Sync {
    fn include_application_plan(
        &self,
        existing_tool_provider_count: &i32,
        incoming_tool_provider_count: &i32,
    ) -> serde_json::Value;
    /// JSON objects with a name model local Tool instances; objects without a name model raw optimizer/toolbox specs that Python passes through without de-duping.
    fn registered_tools(&self, provider_outputs: &serde_json::Value) -> serde_json::Value;
    fn responses_only_application_projection(
        &self,
        name: &String,
        requested_name: &Option<String>,
        has_responses: &bool,
        has_responses_stream: &bool,
        registered_tools: &serde_json::Value,
    ) -> serde_json::Value;
}
