// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure dependency-injection planning. Calling or awaiting dependency functions stays host-specific.
#[async_trait::async_trait]
pub trait RuntimeDependenciesRuntime: Send + Sync {
    fn depends_marker(&self, dependency_name: &String, use_cache: &bool) -> serde_json::Value;
    /// Includes useCache so the contract can pin today's Python behavior: _Depends records it, but resolve() currently ignores it and always uses the process cache.
    fn resolve_dependency_plan(
        &self,
        cache_keys: &Vec<String>,
        dependency_name: &String,
        use_cache: &bool,
    ) -> serde_json::Value;
}
