// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Pure Teams streaming payload builders.
#[async_trait::async_trait]
pub trait StreamingRuntime: Send + Sync {
    fn append_plan(
        &self,
        finished: &bool,
        current_text: &String,
        delta: &String,
        last_flush: &f64,
        now: &f64,
        min_interval: &f64,
    ) -> serde_json::Value;
    fn capture_stream_id(
        &self,
        current_stream_id: &Option<String>,
        created_id: &Option<String>,
    ) -> Option<String>;
    fn finish_allowed(&self, finished: &bool) -> bool;
    fn finish_text(&self, current_text: &String, override_text: &Option<String>) -> String;
    fn next_flush(&self, last_flush: &f64, now: &f64, emitted: &bool) -> serde_json::Value;
    fn next_sequence(&self, sequence: &i32, is_final: &bool) -> i32;
    fn stream_chunk(
        &self,
        stream_type: &String,
        text: &String,
        stream_id: &Option<String>,
        sequence: &i32,
        is_final: &bool,
        attachments: &serde_json::Value,
        suggestions: &serde_json::Value,
    ) -> serde_json::Value;
    fn update_allowed(&self, finished: &bool, current_text: &String) -> bool;
}
