// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

/// Model-facing tool catalog and function-tool spec seams.
#[async_trait::async_trait]
pub trait ToolCatalogRuntime: Send + Sync {
    fn activity_tool_names(&self) -> serde_json::Value;
    fn agent_tool_names(&self) -> serde_json::Value;
    fn graph_tool_names(&self) -> serde_json::Value;
    fn tool_spec(&self, tool: &serde_json::Value) -> serde_json::Value;
}
