// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
//
// Typed @vector conformance entrypoints (issue #511 Cat 1). Each generic fn
// takes a consumer's REAL typed seam impl and runs the seam's baked-in vectors
// by calling trait methods directly — the idiomatic replacement for the
// stringly HashMap<&str, Adapter> runner + vector_adapters.rs registry. The
// `S: <Seam>` bound makes the compiler prove every op is implemented (E0046),
// so completeness is checked at COMPILE time, not by a runtime map lookup.
// References only the model crate + serde_json + std (no vector_adapters, so
// no cycle); emitted additively beside the stringly runner.
// See docs: reference/vector-conformance.

#![allow(unused_imports, dead_code, non_camel_case_types, unused_variables, unexpected_cfgs, clippy::all)]

use serde_json::Value;

/// Typed @vector conformance for ActivityRuntime. Pass your real `impl ActivityRuntime`; the
/// `S: ActivityRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_activity_runtime_conformance(&ActivityRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_activity_runtime_conformance<S: crate::model::ActivityRuntime + ?Sized>(seam: &S) {
    let ctx = crate::model::context::LoadContext::default();
    // vector: agentic-instance-id
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticAppInstance",
    "agenticAppId": "app-1"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_instance_id(&activity);
        let actual_value = serde_json::to_value(actual).expect("agentic-instance-id: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"app-1"
"####,
        )
        .expect("agentic-instance-id: expected parses");
        assert_eq!(actual_value, expected, "agentic-instance-id misrouted");
    }
    // vector: agentic-instance-id-empty-string
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticAppInstance",
    "agenticAppId": ""
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_instance_id(&activity);
        let actual_value = serde_json::to_value(actual).expect("agentic-instance-id-empty-string: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("agentic-instance-id-empty-string: expected parses");
        assert_eq!(actual_value, expected, "agentic-instance-id-empty-string misrouted");
    }
    // vector: agentic-recipient-role
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticAppInstance"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.is_agentic_request(&activity);
        let actual_value = serde_json::to_value(actual).expect("agentic-recipient-role: serialize");
        let expected: Value = serde_json::from_str(
            r####"
true
"####,
        )
        .expect("agentic-recipient-role: expected parses");
        assert_eq!(actual_value, expected, "agentic-recipient-role misrouted");
    }
    // vector: agentic-tenant-falls-back-to-conversation
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticAppInstance"
  },
  "conversation": {
    "tenantId": "tenant-conversation"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_tenant_id(&activity);
        let actual_value = serde_json::to_value(actual).expect("agentic-tenant-falls-back-to-conversation: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"tenant-conversation"
"####,
        )
        .expect("agentic-tenant-falls-back-to-conversation: expected parses");
        assert_eq!(actual_value, expected, "agentic-tenant-falls-back-to-conversation misrouted");
    }
    // vector: agentic-tenant-prefers-recipient
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticAppInstance",
    "tenantId": "tenant-recipient"
  },
  "conversation": {
    "tenantId": "tenant-conversation"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_tenant_id(&activity);
        let actual_value = serde_json::to_value(actual).expect("agentic-tenant-prefers-recipient: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"tenant-recipient"
"####,
        )
        .expect("agentic-tenant-prefers-recipient: expected parses");
        assert_eq!(actual_value, expected, "agentic-tenant-prefers-recipient misrouted");
    }
    // vector: agentic-tenant-skips-empty-conversation
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticAppInstance"
  },
  "conversation": {
    "tenantId": ""
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_tenant_id(&activity);
        let actual_value = serde_json::to_value(actual).expect("agentic-tenant-skips-empty-conversation: serialize");
        let expected: Value = serde_json::from_str(
            r####"
null
"####,
        )
        .expect("agentic-tenant-skips-empty-conversation: expected parses");
        assert_eq!(actual_value, expected, "agentic-tenant-skips-empty-conversation misrouted");
    }
    // vector: agentic-tenant-skips-empty-recipient
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticAppInstance",
    "tenantId": ""
  },
  "conversation": {
    "tenantId": "tenant-conversation"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_tenant_id(&activity);
        let actual_value = serde_json::to_value(actual).expect("agentic-tenant-skips-empty-recipient: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"tenant-conversation"
"####,
        )
        .expect("agentic-tenant-skips-empty-recipient: expected parses");
        assert_eq!(actual_value, expected, "agentic-tenant-skips-empty-recipient misrouted");
    }
    // vector: agentic-user-id
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticUser",
    "agenticUserId": "agent-user-1"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_user(&activity);
        let actual_value = serde_json::to_value(actual).expect("agentic-user-id: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"agent-user-1"
"####,
        )
        .expect("agentic-user-id: expected parses");
        assert_eq!(actual_value, expected, "agentic-user-id misrouted");
    }
    // vector: agentic-user-id-empty-string
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticUser",
    "agenticUserId": ""
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_user(&activity);
        let actual_value = serde_json::to_value(actual).expect("agentic-user-id-empty-string: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("agentic-user-id-empty-string: expected parses");
        assert_eq!(actual_value, expected, "agentic-user-id-empty-string misrouted");
    }
    // vector: agentic-user-recipient-role
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticUser"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.is_agentic_request(&activity);
        let actual_value = serde_json::to_value(actual).expect("agentic-user-recipient-role: serialize");
        let expected: Value = serde_json::from_str(
            r####"
true
"####,
        )
        .expect("agentic-user-recipient-role: expected parses");
        assert_eq!(actual_value, expected, "agentic-user-recipient-role misrouted");
    }
    // vector: bot-recipient-role
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "bot"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.is_agentic_request(&activity);
        let actual_value = serde_json::to_value(actual).expect("bot-recipient-role: serialize");
        let expected: Value = serde_json::from_str(
            r####"
false
"####,
        )
        .expect("bot-recipient-role: expected parses");
        assert_eq!(actual_value, expected, "bot-recipient-role misrouted");
    }
    // vector: channel-empty-after-trim
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "channelId": "  "
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.channel(&activity);
        let actual_value = serde_json::to_value(actual).expect("channel-empty-after-trim: serialize");
        let expected: Value = serde_json::from_str(
            r####"
null
"####,
        )
        .expect("channel-empty-after-trim: expected parses");
        assert_eq!(actual_value, expected, "channel-empty-after-trim misrouted");
    }
    // vector: channel-with-suffix
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "channelId": "msteams:tenant"
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.channel(&activity);
        let actual_value = serde_json::to_value(actual).expect("channel-with-suffix: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"msteams"
"####,
        )
        .expect("channel-with-suffix: expected parses");
        assert_eq!(actual_value, expected, "channel-with-suffix misrouted");
    }
    // vector: channel-without-suffix
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "channelId": "msteams"
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.channel(&activity);
        let actual_value = serde_json::to_value(actual).expect("channel-without-suffix: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"msteams"
"####,
        )
        .expect("channel-without-suffix: expected parses");
        assert_eq!(actual_value, expected, "channel-without-suffix misrouted");
    }
    // vector: mention-absent-entities
    {
        let activity = crate::model::Activity::from_json(
            r####"
{}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.mentions(&activity);
        let expected: Vec<crate::model::Mention> = {
            let items: Vec<Value> = serde_json::from_str(
                r####"
[]
"####,
            )
            .expect("mention-absent-entities: expected parses");
            items
                .iter()
                .map(|item| crate::model::Mention::from_json(&item.to_string(), &ctx)
                    .expect("mention-absent-entities: expected element parses"))
                .collect()
        };
        assert_eq!(actual, expected, "mention-absent-entities misrouted");
    }
    // vector: mention-entities-only
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "entities": [
    {
      "type": "Mention",
      "text": "<at>Castia</at>",
      "mentioned": {
        "id": "bot-1"
      }
    },
    {
      "type": "clientInfo"
    }
  ]
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.mentions(&activity);
        let expected: Vec<crate::model::Mention> = {
            let items: Vec<Value> = serde_json::from_str(
                r####"
[
  {
    "type": "Mention",
    "text": "<at>Castia</at>",
    "mentioned": {
      "id": "bot-1"
    }
  }
]
"####,
            )
            .expect("mention-entities-only: expected parses");
            items
                .iter()
                .map(|item| crate::model::Mention::from_json(&item.to_string(), &ctx)
                    .expect("mention-entities-only: expected element parses"))
                .collect()
        };
        assert_eq!(actual, expected, "mention-entities-only misrouted");
    }
    // vector: mention-lowercase-entity
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "entities": [
    {
      "type": "mention",
      "text": "<at>Castia</at>",
      "mentioned": {
        "id": "bot-1"
      }
    }
  ]
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.mentions(&activity);
        let expected: Vec<crate::model::Mention> = {
            let items: Vec<Value> = serde_json::from_str(
                r####"
[
  {
    "type": "mention",
    "text": "<at>Castia</at>",
    "mentioned": {
      "id": "bot-1"
    }
  }
]
"####,
            )
            .expect("mention-lowercase-entity: expected parses");
            items
                .iter()
                .map(|item| crate::model::Mention::from_json(&item.to_string(), &ctx)
                    .expect("mention-lowercase-entity: expected element parses"))
                .collect()
        };
        assert_eq!(actual, expected, "mention-lowercase-entity misrouted");
    }
    // vector: missing-recipient-role
    {
        let activity = crate::model::Activity::from_json(
            r####"
{}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.is_agentic_request(&activity);
        let actual_value = serde_json::to_value(actual).expect("missing-recipient-role: serialize");
        let expected: Value = serde_json::from_str(
            r####"
false
"####,
        )
        .expect("missing-recipient-role: expected parses");
        assert_eq!(actual_value, expected, "missing-recipient-role misrouted");
    }
    // vector: non-agentic-instance-id
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "bot",
    "agenticAppId": "app-1"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_instance_id(&activity);
        let actual_value = serde_json::to_value(actual).expect("non-agentic-instance-id: serialize");
        let expected: Value = serde_json::from_str(
            r####"
null
"####,
        )
        .expect("non-agentic-instance-id: expected parses");
        assert_eq!(actual_value, expected, "non-agentic-instance-id misrouted");
    }
    // vector: non-agentic-user-id
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "bot",
    "agenticUserId": "agent-user-1"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_user(&activity);
        let actual_value = serde_json::to_value(actual).expect("non-agentic-user-id: serialize");
        let expected: Value = serde_json::from_str(
            r####"
null
"####,
        )
        .expect("non-agentic-user-id: expected parses");
        assert_eq!(actual_value, expected, "non-agentic-user-id misrouted");
    }
}

/// Typed @vector conformance for ResponsesRuntime. Pass your real `impl ResponsesRuntime`; the
/// `S: ResponsesRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_responses_runtime_conformance(&ResponsesRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_responses_runtime_conformance<S: crate::model::ResponsesRuntime + ?Sized>(seam: &S) {
    // vector: bare-string-items-fall-back-to-last
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
[
  "first",
  "second"
]
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("bare-string-items-fall-back-to-last: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"second"
"####,
        )
        .expect("bare-string-items-fall-back-to-last: expected parses");
        assert_eq!(actual_value, expected, "bare-string-items-fall-back-to-last misrouted");
    }
    // vector: empty-list-is-empty
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
[]
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("empty-list-is-empty: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("empty-list-is-empty: expected parses");
        assert_eq!(actual_value, expected, "empty-list-is-empty misrouted");
    }
    // vector: empty-string
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("empty-string: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("empty-string: expected parses");
        assert_eq!(actual_value, expected, "empty-string misrouted");
    }
    // vector: list-content-parts
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
[
  {
    "role": "user",
    "content": [
      {
        "type": "input_text",
        "text": "part one "
      },
      {
        "type": "input_text",
        "text": "part two"
      }
    ]
  }
]
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("list-content-parts: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"part one part two"
"####,
        )
        .expect("list-content-parts: expected parses");
        assert_eq!(actual_value, expected, "list-content-parts misrouted");
    }
    // vector: list-role-string-content
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
[
  {
    "role": "user",
    "content": "say hi"
  }
]
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("list-role-string-content: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"say hi"
"####,
        )
        .expect("list-role-string-content: expected parses");
        assert_eq!(actual_value, expected, "list-role-string-content misrouted");
    }
    // vector: non-list-non-string-is-empty
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
{
  "role": "user"
}
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("non-list-non-string-is-empty: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("non-list-non-string-is-empty: expected parses");
        assert_eq!(actual_value, expected, "non-list-non-string-is-empty misrouted");
    }
    // vector: null-is-empty
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
{}
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("null-is-empty: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("null-is-empty: expected parses");
        assert_eq!(actual_value, expected, "null-is-empty misrouted");
    }
    // vector: number-is-empty
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
42
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("number-is-empty: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("number-is-empty: expected parses");
        assert_eq!(actual_value, expected, "number-is-empty misrouted");
    }
    // vector: output-text-and-text-part-types
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
[
  {
    "role": "user",
    "content": [
      {
        "type": "output_text",
        "text": "a"
      },
      {
        "type": "text",
        "text": "b"
      }
    ]
  }
]
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("output-text-and-text-part-types: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"ab"
"####,
        )
        .expect("output-text-and-text-part-types: expected parses");
        assert_eq!(actual_value, expected, "output-text-and-text-part-types misrouted");
    }
    // vector: plain-string
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
"hello world"
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("plain-string: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"hello world"
"####,
        )
        .expect("plain-string: expected parses");
        assert_eq!(actual_value, expected, "plain-string misrouted");
    }
    // vector: prefers-last-user-turn
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
[
  {
    "role": "user",
    "content": "first"
  },
  {
    "role": "assistant",
    "content": "reply"
  },
  {
    "role": "user",
    "content": "second"
  }
]
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("prefers-last-user-turn: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"second"
"####,
        )
        .expect("prefers-last-user-turn: expected parses");
        assert_eq!(actual_value, expected, "prefers-last-user-turn misrouted");
    }
    // vector: roleless-item-falls-back
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
[
  {
    "content": "no role here"
  }
]
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("roleless-item-falls-back: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"no role here"
"####,
        )
        .expect("roleless-item-falls-back: expected parses");
        assert_eq!(actual_value, expected, "roleless-item-falls-back misrouted");
    }
    // vector: user-turn-wins-over-later-roleless-without-text
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
[
  {
    "role": "user",
    "content": "the question"
  },
  {
    "role": "assistant",
    "content": ""
  }
]
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("user-turn-wins-over-later-roleless-without-text: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"the question"
"####,
        )
        .expect("user-turn-wins-over-later-roleless-without-text: expected parses");
        assert_eq!(actual_value, expected, "user-turn-wins-over-later-roleless-without-text misrouted");
    }
}
