// <auto-generated by typra-emitter>
// Code generated by Typra emitter; DO NOT EDIT.
//
// Typed @vector conformance entrypoints (issue #511 Cat 1). Each generic fn
// takes a consumer's REAL typed seam impl and runs the seam's baked-in vectors
// by calling trait methods directly — the idiomatic replacement for the
// stringly HashMap<&str, Adapter> runner + vector_adapters.rs registry. The
// `S: <Seam>` bound makes the compiler prove every op is implemented (E0046),
// so completeness is checked at COMPILE time, not by a runtime map lookup.
// References only the model crate + serde_json + std (no vector_adapters, so
// no cycle); emitted additively beside the stringly runner.
// See docs: reference/vector-conformance.

#![allow(
    unused_imports,
    dead_code,
    non_camel_case_types,
    unused_variables,
    unexpected_cfgs,
    clippy::all
)]

use serde_json::Value;

/// Typed @vector conformance for ActivityRuntime. Pass your real `impl ActivityRuntime`; the
/// `S: ActivityRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_activity_runtime_conformance(&ActivityRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_activity_runtime_conformance<S: crate::model::ActivityRuntime + ?Sized>(seam: &S) {
    let ctx = crate::model::context::LoadContext::default();
    // vector: agentic-instance-id
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticAppInstance",
    "agenticAppId": "app-1"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_instance_id(&activity);
        let actual_value = serde_json::to_value(actual).expect("agentic-instance-id: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"app-1"
"####,
        )
        .expect("agentic-instance-id: expected parses");
        assert_eq!(actual_value, expected, "agentic-instance-id misrouted");
    }
    // vector: agentic-instance-id-empty-string
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticAppInstance",
    "agenticAppId": ""
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_instance_id(&activity);
        let actual_value =
            serde_json::to_value(actual).expect("agentic-instance-id-empty-string: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("agentic-instance-id-empty-string: expected parses");
        assert_eq!(
            actual_value, expected,
            "agentic-instance-id-empty-string misrouted"
        );
    }
    // vector: agentic-recipient-role
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticAppInstance"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.is_agentic_request(&activity);
        let actual_value = serde_json::to_value(actual).expect("agentic-recipient-role: serialize");
        let expected: Value = serde_json::from_str(
            r####"
true
"####,
        )
        .expect("agentic-recipient-role: expected parses");
        assert_eq!(actual_value, expected, "agentic-recipient-role misrouted");
    }
    // vector: agentic-tenant-falls-back-to-conversation
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticAppInstance"
  },
  "conversation": {
    "tenantId": "tenant-conversation"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_tenant_id(&activity);
        let actual_value = serde_json::to_value(actual)
            .expect("agentic-tenant-falls-back-to-conversation: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"tenant-conversation"
"####,
        )
        .expect("agentic-tenant-falls-back-to-conversation: expected parses");
        assert_eq!(
            actual_value, expected,
            "agentic-tenant-falls-back-to-conversation misrouted"
        );
    }
    // vector: agentic-tenant-prefers-recipient
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticAppInstance",
    "tenantId": "tenant-recipient"
  },
  "conversation": {
    "tenantId": "tenant-conversation"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_tenant_id(&activity);
        let actual_value =
            serde_json::to_value(actual).expect("agentic-tenant-prefers-recipient: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"tenant-recipient"
"####,
        )
        .expect("agentic-tenant-prefers-recipient: expected parses");
        assert_eq!(
            actual_value, expected,
            "agentic-tenant-prefers-recipient misrouted"
        );
    }
    // vector: agentic-tenant-skips-empty-conversation
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticAppInstance"
  },
  "conversation": {
    "tenantId": ""
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_tenant_id(&activity);
        let actual_value = serde_json::to_value(actual)
            .expect("agentic-tenant-skips-empty-conversation: serialize");
        let expected: Value = serde_json::from_str(
            r####"
null
"####,
        )
        .expect("agentic-tenant-skips-empty-conversation: expected parses");
        assert_eq!(
            actual_value, expected,
            "agentic-tenant-skips-empty-conversation misrouted"
        );
    }
    // vector: agentic-tenant-skips-empty-recipient
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticAppInstance",
    "tenantId": ""
  },
  "conversation": {
    "tenantId": "tenant-conversation"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_tenant_id(&activity);
        let actual_value =
            serde_json::to_value(actual).expect("agentic-tenant-skips-empty-recipient: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"tenant-conversation"
"####,
        )
        .expect("agentic-tenant-skips-empty-recipient: expected parses");
        assert_eq!(
            actual_value, expected,
            "agentic-tenant-skips-empty-recipient misrouted"
        );
    }
    // vector: agentic-user-id
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticUser",
    "agenticUserId": "agent-user-1"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_user(&activity);
        let actual_value = serde_json::to_value(actual).expect("agentic-user-id: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"agent-user-1"
"####,
        )
        .expect("agentic-user-id: expected parses");
        assert_eq!(actual_value, expected, "agentic-user-id misrouted");
    }
    // vector: agentic-user-id-empty-string
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticUser",
    "agenticUserId": ""
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_user(&activity);
        let actual_value =
            serde_json::to_value(actual).expect("agentic-user-id-empty-string: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("agentic-user-id-empty-string: expected parses");
        assert_eq!(
            actual_value, expected,
            "agentic-user-id-empty-string misrouted"
        );
    }
    // vector: agentic-user-recipient-role
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticUser"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.is_agentic_request(&activity);
        let actual_value =
            serde_json::to_value(actual).expect("agentic-user-recipient-role: serialize");
        let expected: Value = serde_json::from_str(
            r####"
true
"####,
        )
        .expect("agentic-user-recipient-role: expected parses");
        assert_eq!(
            actual_value, expected,
            "agentic-user-recipient-role misrouted"
        );
    }
    // vector: bot-recipient-role
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "bot"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.is_agentic_request(&activity);
        let actual_value = serde_json::to_value(actual).expect("bot-recipient-role: serialize");
        let expected: Value = serde_json::from_str(
            r####"
false
"####,
        )
        .expect("bot-recipient-role: expected parses");
        assert_eq!(actual_value, expected, "bot-recipient-role misrouted");
    }
    // vector: channel-empty-after-trim
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "channelId": "  "
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.channel(&activity);
        let actual_value =
            serde_json::to_value(actual).expect("channel-empty-after-trim: serialize");
        let expected: Value = serde_json::from_str(
            r####"
null
"####,
        )
        .expect("channel-empty-after-trim: expected parses");
        assert_eq!(actual_value, expected, "channel-empty-after-trim misrouted");
    }
    // vector: channel-with-suffix
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "channelId": "msteams:tenant"
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.channel(&activity);
        let actual_value = serde_json::to_value(actual).expect("channel-with-suffix: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"msteams"
"####,
        )
        .expect("channel-with-suffix: expected parses");
        assert_eq!(actual_value, expected, "channel-with-suffix misrouted");
    }
    // vector: channel-without-suffix
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "channelId": "msteams"
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.channel(&activity);
        let actual_value = serde_json::to_value(actual).expect("channel-without-suffix: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"msteams"
"####,
        )
        .expect("channel-without-suffix: expected parses");
        assert_eq!(actual_value, expected, "channel-without-suffix misrouted");
    }
    // vector: mention-absent-entities
    {
        let activity = crate::model::Activity::from_json(
            r####"
{}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.mentions(&activity);
        let expected: Vec<crate::model::Mention> = {
            let items: Vec<Value> = serde_json::from_str(
                r####"
[]
"####,
            )
            .expect("mention-absent-entities: expected parses");
            items
                .iter()
                .map(|item| {
                    crate::model::Mention::from_json(&item.to_string(), &ctx)
                        .expect("mention-absent-entities: expected element parses")
                })
                .collect()
        };
        assert_eq!(actual, expected, "mention-absent-entities misrouted");
    }
    // vector: mention-entities-only
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "entities": [
    {
      "type": "Mention",
      "text": "<at>Castia</at>",
      "mentioned": {
        "id": "bot-1"
      }
    },
    {
      "type": "clientInfo"
    }
  ]
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.mentions(&activity);
        let expected: Vec<crate::model::Mention> = {
            let items: Vec<Value> = serde_json::from_str(
                r####"
[
  {
    "type": "Mention",
    "text": "<at>Castia</at>",
    "mentioned": {
      "id": "bot-1"
    }
  }
]
"####,
            )
            .expect("mention-entities-only: expected parses");
            items
                .iter()
                .map(|item| {
                    crate::model::Mention::from_json(&item.to_string(), &ctx)
                        .expect("mention-entities-only: expected element parses")
                })
                .collect()
        };
        assert_eq!(actual, expected, "mention-entities-only misrouted");
    }
    // vector: mention-lowercase-entity
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "entities": [
    {
      "type": "mention",
      "text": "<at>Castia</at>",
      "mentioned": {
        "id": "bot-1"
      }
    }
  ]
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.mentions(&activity);
        let expected: Vec<crate::model::Mention> = {
            let items: Vec<Value> = serde_json::from_str(
                r####"
[
  {
    "type": "mention",
    "text": "<at>Castia</at>",
    "mentioned": {
      "id": "bot-1"
    }
  }
]
"####,
            )
            .expect("mention-lowercase-entity: expected parses");
            items
                .iter()
                .map(|item| {
                    crate::model::Mention::from_json(&item.to_string(), &ctx)
                        .expect("mention-lowercase-entity: expected element parses")
                })
                .collect()
        };
        assert_eq!(actual, expected, "mention-lowercase-entity misrouted");
    }
    // vector: missing-recipient-role
    {
        let activity = crate::model::Activity::from_json(
            r####"
{}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.is_agentic_request(&activity);
        let actual_value = serde_json::to_value(actual).expect("missing-recipient-role: serialize");
        let expected: Value = serde_json::from_str(
            r####"
false
"####,
        )
        .expect("missing-recipient-role: expected parses");
        assert_eq!(actual_value, expected, "missing-recipient-role misrouted");
    }
    // vector: non-agentic-instance-id
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "bot",
    "agenticAppId": "app-1"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_instance_id(&activity);
        let actual_value =
            serde_json::to_value(actual).expect("non-agentic-instance-id: serialize");
        let expected: Value = serde_json::from_str(
            r####"
null
"####,
        )
        .expect("non-agentic-instance-id: expected parses");
        assert_eq!(actual_value, expected, "non-agentic-instance-id misrouted");
    }
    // vector: non-agentic-user-id
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "bot",
    "agenticUserId": "agent-user-1"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_user(&activity);
        let actual_value = serde_json::to_value(actual).expect("non-agentic-user-id: serialize");
        let expected: Value = serde_json::from_str(
            r####"
null
"####,
        )
        .expect("non-agentic-user-id: expected parses");
        assert_eq!(actual_value, expected, "non-agentic-user-id misrouted");
    }
}

/// Typed @vector conformance for BuildTestingRuntime. Pass your real `impl BuildTestingRuntime`; the
/// `S: BuildTestingRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_build_testing_runtime_conformance(&BuildTestingRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_build_testing_runtime_conformance<S: crate::model::BuildTestingRuntime + ?Sized>(
    seam: &S,
) {
    // vector: test-timeout-accepts-positive-finite
    {
        let timeout: f64 = serde_json::from_str(
            r####"
60
"####,
        )
        .expect("timeout parses");
        let actual = seam.validate_test_timeout(&timeout);
        let actual_value =
            serde_json::to_value(actual).expect("test-timeout-accepts-positive-finite: serialize");
        let expected: Value = serde_json::from_str(
            r####"
60
"####,
        )
        .expect("test-timeout-accepts-positive-finite: expected parses");
        assert_eq!(
            actual_value, expected,
            "test-timeout-accepts-positive-finite misrouted"
        );
    }
    // skipped: test-timeout-rejects-negative — expectedError on a @sync op has no typed error channel
    // skipped: test-timeout-rejects-zero — expectedError on a @sync op has no typed error channel
}

/// Typed @vector conformance for ChatRuntime. Pass your real `impl ChatRuntime`; the
/// `S: ChatRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_chat_runtime_conformance(&ChatRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_chat_runtime_conformance<S: crate::model::ChatRuntime + ?Sized>(seam: &S) {
    // vector: last-user-turn
    {
        let messages: serde_json::Value = serde_json::from_str(
            r####"
[
  {
    "role": "user",
    "content": "first"
  },
  {
    "role": "assistant",
    "content": "reply"
  },
  {
    "role": "user",
    "content": "second"
  }
]
"####,
        )
        .expect("messages parses");
        let actual = seam.last_user_text(&messages);
        let actual_value = serde_json::to_value(actual).expect("last-user-turn: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"second"
"####,
        )
        .expect("last-user-turn: expected parses");
        assert_eq!(actual_value, expected, "last-user-turn misrouted");
    }
    // vector: missing-content-is-empty
    {
        let messages: serde_json::Value = serde_json::from_str(
            r####"
[
  {
    "role": "user"
  }
]
"####,
        )
        .expect("messages parses");
        let actual = seam.last_user_text(&messages);
        let actual_value =
            serde_json::to_value(actual).expect("missing-content-is-empty: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("missing-content-is-empty: expected parses");
        assert_eq!(actual_value, expected, "missing-content-is-empty misrouted");
    }
    // vector: missing-user-turn
    {
        let messages: serde_json::Value = serde_json::from_str(
            r####"
[
  {
    "role": "assistant",
    "content": "reply"
  }
]
"####,
        )
        .expect("messages parses");
        let actual = seam.last_user_text(&messages);
        let actual_value = serde_json::to_value(actual).expect("missing-user-turn: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("missing-user-turn: expected parses");
        assert_eq!(actual_value, expected, "missing-user-turn misrouted");
    }
    // vector: null-messages
    {
        let messages: serde_json::Value = serde_json::from_str(
            r####"
{}
"####,
        )
        .expect("messages parses");
        let actual = seam.last_user_text(&messages);
        let actual_value = serde_json::to_value(actual).expect("null-messages: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("null-messages: expected parses");
        assert_eq!(actual_value, expected, "null-messages misrouted");
    }
}

/// Typed @vector conformance for DeliveryAzdRuntime. Pass your real `impl DeliveryAzdRuntime`; the
/// `S: DeliveryAzdRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_delivery_azd_runtime_conformance(&DeliveryAzdRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_delivery_azd_runtime_conformance<S: crate::model::DeliveryAzdRuntime + ?Sized>(
    seam: &S,
) {
    // vector: azd-command-error-redacts-output
    {
        let command: Vec<String> = serde_json::from_str(
            r####"
[
  "deploy",
  "smoke",
  "--no-prompt",
  "--secret",
  "token"
]
"####,
        )
        .expect("command parses");
        let return_code: i32 = serde_json::from_str(
            r####"
1
"####,
        )
        .expect("returnCode parses");
        let stdout: String = serde_json::from_str(
            r####"
"SECRET-STDOUT"
"####,
        )
        .expect("stdout parses");
        let stderr: String = serde_json::from_str(
            r####"
"SECRET-STDERR"
"####,
        )
        .expect("stderr parses");
        let actual = seam.command_error_message(&command, &return_code, &stdout, &stderr);
        let actual_value =
            serde_json::to_value(actual).expect("azd-command-error-redacts-output: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"azd deploy smoke --no-prompt exited 1; inspect deployment logs and verify remote state before retrying"
"####,
        )
        .expect("azd-command-error-redacts-output: expected parses");
        assert_eq!(
            actual_value, expected,
            "azd-command-error-redacts-output misrouted"
        );
    }
}

/// Typed @vector conformance for DeliveryManifestRuntime. Pass your real `impl DeliveryManifestRuntime`; the
/// `S: DeliveryManifestRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_delivery_manifest_runtime_conformance(&DeliveryManifestRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_delivery_manifest_runtime_conformance<
    S: crate::model::DeliveryManifestRuntime + ?Sized,
>(
    seam: &S,
) {
    // vector: publishable-protocols-filters-local-only
    {
        let registered_protocols: Vec<String> = serde_json::from_str(
            r####"
[
  "activity",
  "chat",
  "responses"
]
"####,
        )
        .expect("registeredProtocols parses");
        let actual = seam.publishable_protocols(&registered_protocols);
        let actual_value = serde_json::to_value(actual)
            .expect("publishable-protocols-filters-local-only: serialize");
        let expected: Value = serde_json::from_str(
            r####"
[
  "activity",
  "responses"
]
"####,
        )
        .expect("publishable-protocols-filters-local-only: expected parses");
        assert_eq!(
            actual_value, expected,
            "publishable-protocols-filters-local-only misrouted"
        );
    }
    // vector: skipped-protocols-captures-local-only
    {
        let registered_protocols: Vec<String> = serde_json::from_str(
            r####"
[
  "activity",
  "chat",
  "responses"
]
"####,
        )
        .expect("registeredProtocols parses");
        let actual = seam.skipped_protocols(&registered_protocols);
        let actual_value =
            serde_json::to_value(actual).expect("skipped-protocols-captures-local-only: serialize");
        let expected: Value = serde_json::from_str(
            r####"
[
  "chat"
]
"####,
        )
        .expect("skipped-protocols-captures-local-only: expected parses");
        assert_eq!(
            actual_value, expected,
            "skipped-protocols-captures-local-only misrouted"
        );
    }
}

/// Typed @vector conformance for IdentityRuntime. Pass your real `impl IdentityRuntime`; the
/// `S: IdentityRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_identity_runtime_conformance(&IdentityRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_identity_runtime_conformance<S: crate::model::IdentityRuntime + ?Sized>(seam: &S) {
    let ctx = crate::model::context::LoadContext::default();
    // vector: agentic-user-id
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticUser",
    "agenticUserId": "user-1"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_user_id(&activity);
        let actual_value = serde_json::to_value(actual).expect("agentic-user-id: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"user-1"
"####,
        )
        .expect("agentic-user-id: expected parses");
        assert_eq!(actual_value, expected, "agentic-user-id misrouted");
    }
    // vector: app-instance-has-no-mailbox
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticAppInstance",
    "agenticUserId": "user-1"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.agentic_user_id(&activity);
        let actual_value =
            serde_json::to_value(actual).expect("app-instance-has-no-mailbox: serialize");
        let expected: Value = serde_json::from_str(
            r####"
null
"####,
        )
        .expect("app-instance-has-no-mailbox: expected parses");
        assert_eq!(
            actual_value, expected,
            "app-instance-has-no-mailbox misrouted"
        );
    }
    // skipped: require-agentic-user-fails — expectedError on a @sync op has no typed error channel
    // vector: require-agentic-user-pass
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "recipient": {
    "role": "agenticUser",
    "agenticUserId": "user-1"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.require_agentic_user(&activity);
        let actual_value =
            serde_json::to_value(actual).expect("require-agentic-user-pass: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"user-1"
"####,
        )
        .expect("require-agentic-user-pass: expected parses");
        assert_eq!(
            actual_value, expected,
            "require-agentic-user-pass misrouted"
        );
    }
}

/// Typed @vector conformance for IntegrationsGraphRuntime. Pass your real `impl IntegrationsGraphRuntime`; the
/// `S: IntegrationsGraphRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_integrations_graph_runtime_conformance(&IntegrationsGraphRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_integrations_graph_runtime_conformance<
    S: crate::model::IntegrationsGraphRuntime + ?Sized,
>(
    seam: &S,
) {
    // vector: drive-upload-url-encodes-path-segments
    {
        let path: String = serde_json::from_str(
            r####"
"/Reports/Q1 Plan #1.md"
"####,
        )
        .expect("path parses");
        let actual = seam.drive_upload_url(&path);
        let actual_value = serde_json::to_value(actual)
            .expect("drive-upload-url-encodes-path-segments: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"https://graph.microsoft.com/v1.0/me/drive/root:/Reports/Q1%20Plan%20%231.md:/content"
"####,
        )
        .expect("drive-upload-url-encodes-path-segments: expected parses");
        assert_eq!(
            actual_value, expected,
            "drive-upload-url-encodes-path-segments misrouted"
        );
    }
    // vector: drive-upload-url-encodes-python-quote-reserved-chars
    {
        let path: String = serde_json::from_str(
            r####"
"/Reports/100% done: Sales & Marketing (final).md"
"####,
        )
        .expect("path parses");
        let actual = seam.drive_upload_url(&path);
        let actual_value = serde_json::to_value(actual)
            .expect("drive-upload-url-encodes-python-quote-reserved-chars: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"https://graph.microsoft.com/v1.0/me/drive/root:/Reports/100%25%20done%3A%20Sales%20%26%20Marketing%20%28final%29.md:/content"
"####,
        )
        .expect("drive-upload-url-encodes-python-quote-reserved-chars: expected parses");
        assert_eq!(
            actual_value, expected,
            "drive-upload-url-encodes-python-quote-reserved-chars misrouted"
        );
    }
    // vector: mailbox-url-adds-unread-filter
    {
        let top: i32 = serde_json::from_str(
            r####"
0
"####,
        )
        .expect("top parses");
        let unread_only: bool = serde_json::from_str(
            r####"
true
"####,
        )
        .expect("unreadOnly parses");
        let actual = seam.mailbox_messages_url(&top, &unread_only);
        let actual_value =
            serde_json::to_value(actual).expect("mailbox-url-adds-unread-filter: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"https://graph.microsoft.com/v1.0/me/messages?%24top=1&%24select=id%2Cfrom%2Csubject%2CreceivedDateTime%2CisRead%2CbodyPreview&%24orderby=receivedDateTime+desc&%24filter=isRead+eq+false"
"####,
        )
        .expect("mailbox-url-adds-unread-filter: expected parses");
        assert_eq!(
            actual_value, expected,
            "mailbox-url-adds-unread-filter misrouted"
        );
    }
    // vector: mailbox-url-clamps-top-and-selects-newest
    {
        let top: i32 = serde_json::from_str(
            r####"
99
"####,
        )
        .expect("top parses");
        let unread_only: bool = serde_json::from_str(
            r####"
false
"####,
        )
        .expect("unreadOnly parses");
        let actual = seam.mailbox_messages_url(&top, &unread_only);
        let actual_value = serde_json::to_value(actual)
            .expect("mailbox-url-clamps-top-and-selects-newest: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"https://graph.microsoft.com/v1.0/me/messages?%24top=25&%24select=id%2Cfrom%2Csubject%2CreceivedDateTime%2CisRead%2CbodyPreview&%24orderby=receivedDateTime+desc"
"####,
        )
        .expect("mailbox-url-clamps-top-and-selects-newest: expected parses");
        assert_eq!(
            actual_value, expected,
            "mailbox-url-clamps-top-and-selects-newest misrouted"
        );
    }
}

/// Typed @vector conformance for IntegrationsToolboxRuntime. Pass your real `impl IntegrationsToolboxRuntime`; the
/// `S: IntegrationsToolboxRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_integrations_toolbox_runtime_conformance(&IntegrationsToolboxRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_integrations_toolbox_runtime_conformance<
    S: crate::model::IntegrationsToolboxRuntime + ?Sized,
>(
    seam: &S,
) {
    // vector: compose-toolbox-endpoint-unversioned
    {
        let project_endpoint: String = serde_json::from_str(
            r####"
"https://acct.services.ai.azure.com/api/projects/proj/"
"####,
        )
        .expect("projectEndpoint parses");
        let name: String = serde_json::from_str(
            r####"
"hal-smoke"
"####,
        )
        .expect("name parses");
        let version: Option<String> = serde_json::from_str(
            r####"
{}
"####,
        )
        .expect("version parses");
        let actual = seam.compose_toolbox_endpoint(&project_endpoint, &name, &version);
        let actual_value =
            serde_json::to_value(actual).expect("compose-toolbox-endpoint-unversioned: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"https://acct.services.ai.azure.com/api/projects/proj/toolboxes/hal-smoke/mcp?api-version=v1"
"####,
        )
        .expect("compose-toolbox-endpoint-unversioned: expected parses");
        assert_eq!(
            actual_value, expected,
            "compose-toolbox-endpoint-unversioned misrouted"
        );
    }
    // vector: compose-toolbox-endpoint-versioned
    {
        let project_endpoint: String = serde_json::from_str(
            r####"
"https://acct.services.ai.azure.com/api/projects/proj"
"####,
        )
        .expect("projectEndpoint parses");
        let name: String = serde_json::from_str(
            r####"
"hal-smoke"
"####,
        )
        .expect("name parses");
        let version: Option<String> = serde_json::from_str(
            r####"
"3"
"####,
        )
        .expect("version parses");
        let actual = seam.compose_toolbox_endpoint(&project_endpoint, &name, &version);
        let actual_value =
            serde_json::to_value(actual).expect("compose-toolbox-endpoint-versioned: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"https://acct.services.ai.azure.com/api/projects/proj/toolboxes/hal-smoke/versions/3/mcp?api-version=v1"
"####,
        )
        .expect("compose-toolbox-endpoint-versioned: expected parses");
        assert_eq!(
            actual_value, expected,
            "compose-toolbox-endpoint-versioned misrouted"
        );
    }
    // vector: platform-endpoint-env-normalizes-name
    {
        let name: String = serde_json::from_str(
            r####"
"My.Box 2"
"####,
        )
        .expect("name parses");
        let actual = seam.platform_endpoint_env(&name);
        let actual_value =
            serde_json::to_value(actual).expect("platform-endpoint-env-normalizes-name: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"TOOLBOX_MY_BOX_2_MCP_ENDPOINT"
"####,
        )
        .expect("platform-endpoint-env-normalizes-name: expected parses");
        assert_eq!(
            actual_value, expected,
            "platform-endpoint-env-normalizes-name misrouted"
        );
    }
    // vector: resolve-toolbox-composes-from-project-and-name
    {
        let env: serde_json::Value = serde_json::from_str(
            r####"
{
  "FOUNDRY_PROJECT_ENDPOINT": "https://acct.services.ai.azure.com/api/projects/proj",
  "TOOLBOX_NAME": "hal-smoke"
}
"####,
        )
        .expect("env parses");
        let actual = seam.resolve_toolbox_endpoint(&env);
        let actual_value = serde_json::to_value(actual)
            .expect("resolve-toolbox-composes-from-project-and-name: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"https://acct.services.ai.azure.com/api/projects/proj/toolboxes/hal-smoke/mcp?api-version=v1"
"####,
        )
        .expect("resolve-toolbox-composes-from-project-and-name: expected parses");
        assert_eq!(
            actual_value, expected,
            "resolve-toolbox-composes-from-project-and-name misrouted"
        );
    }
    // vector: resolve-toolbox-full-url-wins
    {
        let env: serde_json::Value = serde_json::from_str(
            r####"
{
  "TOOLBOX_ENDPOINT": "https://explicit/mcp",
  "FOUNDRY_PROJECT_ENDPOINT": "https://acct.services.ai.azure.com/api/projects/proj",
  "TOOLBOX_NAME": "ignored"
}
"####,
        )
        .expect("env parses");
        let actual = seam.resolve_toolbox_endpoint(&env);
        let actual_value =
            serde_json::to_value(actual).expect("resolve-toolbox-full-url-wins: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"https://explicit/mcp"
"####,
        )
        .expect("resolve-toolbox-full-url-wins: expected parses");
        assert_eq!(
            actual_value, expected,
            "resolve-toolbox-full-url-wins misrouted"
        );
    }
    // vector: resolve-toolbox-mcp-endpoint-alias
    {
        let env: serde_json::Value = serde_json::from_str(
            r####"
{
  "TOOLBOX_MCP_ENDPOINT": "https://alias/mcp"
}
"####,
        )
        .expect("env parses");
        let actual = seam.resolve_toolbox_endpoint(&env);
        let actual_value =
            serde_json::to_value(actual).expect("resolve-toolbox-mcp-endpoint-alias: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"https://alias/mcp"
"####,
        )
        .expect("resolve-toolbox-mcp-endpoint-alias: expected parses");
        assert_eq!(
            actual_value, expected,
            "resolve-toolbox-mcp-endpoint-alias misrouted"
        );
    }
    // vector: resolve-toolbox-none-when-name-empty
    {
        let env: serde_json::Value = serde_json::from_str(
            r####"
{
  "FOUNDRY_PROJECT_ENDPOINT": "https://acct.services.ai.azure.com/api/projects/proj",
  "TOOLBOX_NAME": ""
}
"####,
        )
        .expect("env parses");
        let actual = seam.resolve_toolbox_endpoint(&env);
        let actual_value =
            serde_json::to_value(actual).expect("resolve-toolbox-none-when-name-empty: serialize");
        let expected: Value = serde_json::from_str(
            r####"
null
"####,
        )
        .expect("resolve-toolbox-none-when-name-empty: expected parses");
        assert_eq!(
            actual_value, expected,
            "resolve-toolbox-none-when-name-empty misrouted"
        );
    }
    // vector: resolve-toolbox-none-when-unset
    {
        let env: serde_json::Value = serde_json::from_str(
            r####"
{}
"####,
        )
        .expect("env parses");
        let actual = seam.resolve_toolbox_endpoint(&env);
        let actual_value =
            serde_json::to_value(actual).expect("resolve-toolbox-none-when-unset: serialize");
        let expected: Value = serde_json::from_str(
            r####"
null
"####,
        )
        .expect("resolve-toolbox-none-when-unset: expected parses");
        assert_eq!(
            actual_value, expected,
            "resolve-toolbox-none-when-unset misrouted"
        );
    }
    // vector: resolve-toolbox-platform-native-before-compose
    {
        let env: serde_json::Value = serde_json::from_str(
            r####"
{
  "TOOLBOX_NAME": "hal-smoke",
  "TOOLBOX_HAL_SMOKE_MCP_ENDPOINT": "https://platform/mcp",
  "FOUNDRY_PROJECT_ENDPOINT": "https://acct.services.ai.azure.com/api/projects/proj"
}
"####,
        )
        .expect("env parses");
        let actual = seam.resolve_toolbox_endpoint(&env);
        let actual_value = serde_json::to_value(actual)
            .expect("resolve-toolbox-platform-native-before-compose: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"https://platform/mcp"
"####,
        )
        .expect("resolve-toolbox-platform-native-before-compose: expected parses");
        assert_eq!(
            actual_value, expected,
            "resolve-toolbox-platform-native-before-compose misrouted"
        );
    }
}

/// Typed @vector conformance for InvocationsRuntime. Pass your real `impl InvocationsRuntime`; the
/// `S: InvocationsRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_invocations_runtime_conformance(&InvocationsRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_invocations_runtime_conformance<S: crate::model::InvocationsRuntime + ?Sized>(seam: &S) {
    // vector: bare-string
    {
        let body: serde_json::Value = serde_json::from_str(
            r####"
"hello"
"####,
        )
        .expect("body parses");
        let actual = seam.input_text(&body);
        let actual_value = serde_json::to_value(actual).expect("bare-string: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"hello"
"####,
        )
        .expect("bare-string: expected parses");
        assert_eq!(actual_value, expected, "bare-string misrouted");
    }
    // vector: input-field
    {
        let body: serde_json::Value = serde_json::from_str(
            r####"
{
  "input": "hello"
}
"####,
        )
        .expect("body parses");
        let actual = seam.input_text(&body);
        let actual_value = serde_json::to_value(actual).expect("input-field: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"hello"
"####,
        )
        .expect("input-field: expected parses");
        assert_eq!(actual_value, expected, "input-field misrouted");
    }
    // vector: message-field
    {
        let body: serde_json::Value = serde_json::from_str(
            r####"
{
  "message": "hello"
}
"####,
        )
        .expect("body parses");
        let actual = seam.input_text(&body);
        let actual_value = serde_json::to_value(actual).expect("message-field: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"hello"
"####,
        )
        .expect("message-field: expected parses");
        assert_eq!(actual_value, expected, "message-field misrouted");
    }
    // vector: message-wins-over-input
    {
        let body: serde_json::Value = serde_json::from_str(
            r####"
{
  "message": "message",
  "input": "input"
}
"####,
        )
        .expect("body parses");
        let actual = seam.input_text(&body);
        let actual_value =
            serde_json::to_value(actual).expect("message-wins-over-input: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"message"
"####,
        )
        .expect("message-wins-over-input: expected parses");
        assert_eq!(actual_value, expected, "message-wins-over-input misrouted");
    }
    // vector: non-string-fields-are-empty
    {
        let body: serde_json::Value = serde_json::from_str(
            r####"
{
  "message": 42,
  "input": true
}
"####,
        )
        .expect("body parses");
        let actual = seam.input_text(&body);
        let actual_value =
            serde_json::to_value(actual).expect("non-string-fields-are-empty: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("non-string-fields-are-empty: expected parses");
        assert_eq!(
            actual_value, expected,
            "non-string-fields-are-empty misrouted"
        );
    }
    // vector: null-is-empty
    {
        let body: serde_json::Value = serde_json::from_str(
            r####"
{}
"####,
        )
        .expect("body parses");
        let actual = seam.input_text(&body);
        let actual_value = serde_json::to_value(actual).expect("null-is-empty: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("null-is-empty: expected parses");
        assert_eq!(actual_value, expected, "null-is-empty misrouted");
    }
}

/// Typed @vector conformance for LifecycleOperationsRuntime. Pass your real `impl LifecycleOperationsRuntime`; the
/// `S: LifecycleOperationsRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_lifecycle_operations_runtime_conformance(&LifecycleOperationsRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_lifecycle_operations_runtime_conformance<
    S: crate::model::LifecycleOperationsRuntime + ?Sized,
>(
    seam: &S,
) {
    // vector: dataset-jsonl-exports-heldout
    {
        let dataset: serde_json::Value = serde_json::from_str(
            r####"
{
  "schemaVersion": 1,
  "kind": "dataset",
  "examples": [
    {
      "input": "question-4",
      "reference": "reference-4",
      "group": "ada4f2d6999ab34adfb25b7924fe007ceebd8575555c8fb9e98e14bd440730a1",
      "provenance": [
        "trace-4"
      ],
      "reviewers": [
        "human-reviewer"
      ],
      "referenceOrigins": [
        "human"
      ]
    },
    {
      "input": "question-3",
      "reference": "reference-3",
      "group": "207f3f2c40a278c4c0373565e29ee0157614384a3c7285510fbaf3e446d71033",
      "provenance": [
        "trace-3"
      ],
      "reviewers": [
        "human-reviewer"
      ],
      "referenceOrigins": [
        "human"
      ]
    },
    {
      "input": "question-1",
      "reference": "reference-1",
      "group": "3d4d007868105f5324540be8e475012d789e11a404abea386c89b8e5616cac18",
      "provenance": [
        "trace-1"
      ],
      "reviewers": [
        "human-reviewer"
      ],
      "referenceOrigins": [
        "human"
      ]
    },
    {
      "input": "question-5",
      "reference": "reference-5",
      "group": "e6cc1575b9e2288b0b5f0c6abd927b77b2a0a740a0fad986c5cf8e0c95f09b9e",
      "provenance": [
        "trace-5"
      ],
      "reviewers": [
        "human-reviewer"
      ],
      "referenceOrigins": [
        "human"
      ]
    },
    {
      "input": "question-0",
      "reference": "reference-0",
      "group": "69e88732eac8006038bbfaff8641b2e67221dd5d1e1fc80dcd83a3e71cfd82c7",
      "provenance": [
        "trace-0"
      ],
      "reviewers": [
        "human-reviewer"
      ],
      "referenceOrigins": [
        "human"
      ]
    },
    {
      "input": "question-2",
      "reference": "reference-2",
      "group": "f8c77c9e7194fc372600650152a562be9321bce0c51fbfdc9bbd8eeb894a0e2a",
      "provenance": [
        "trace-2"
      ],
      "reviewers": [
        "human-reviewer"
      ],
      "referenceOrigins": [
        "human"
      ]
    }
  ],
  "trainIds": [
    "229f6d6e9faeec2efc159c566693ac0452a360088f86ea457a1c34057cfe62e1",
    "378e032c99714dc149845afc558df0d658421ed86673d0579da0fc32eae2d39b",
    "d351e278dadc78bec9ad701fbcee682f73a485f5be9e63999b55661db26cf357",
    "d3d9fa86e6735affbb18ca08a7306a6fe3cd8f6b335422e44ef85591d5b7ddb1"
  ],
  "heldoutIds": [
    "bdf737bc87a151c7436de89d535aee9b5dfbc210f912fd1053a7512aa9ba1f20",
    "eb8419dfae8418e28509b282030b030f69e9c0b361a674e023ee59ee6ed04cf3"
  ],
  "seed": "castia",
  "redactionVersion": "v1"
}
"####,
        )
        .expect("dataset parses");
        let split: String = serde_json::from_str(
            r####"
"heldout"
"####,
        )
        .expect("split parses");
        let actual = seam.dataset_jsonl(&dataset, &split);
        let actual_value =
            serde_json::to_value(actual).expect("dataset-jsonl-exports-heldout: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"{\"example_id\":\"bdf737bc87a151c7436de89d535aee9b5dfbc210f912fd1053a7512aa9ba1f20\",\"messages\":[{\"content\":\"question-1\",\"role\":\"user\"}],\"provenance\":[\"trace-1\"],\"reference\":\"reference-1\",\"reference_origins\":[\"human\"]}\n{\"example_id\":\"eb8419dfae8418e28509b282030b030f69e9c0b361a674e023ee59ee6ed04cf3\",\"messages\":[{\"content\":\"question-2\",\"role\":\"user\"}],\"provenance\":[\"trace-2\"],\"reference\":\"reference-2\",\"reference_origins\":[\"human\"]}\n"
"####,
        )
        .expect("dataset-jsonl-exports-heldout: expected parses");
        assert_eq!(
            actual_value, expected,
            "dataset-jsonl-exports-heldout misrouted"
        );
    }
    // skipped: dataset-jsonl-rejects-unknown-split — expectedError on a @sync op has no typed error channel
}

/// Typed @vector conformance for LifecycleRecordsRuntime. Pass your real `impl LifecycleRecordsRuntime`; the
/// `S: LifecycleRecordsRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_lifecycle_records_runtime_conformance(&LifecycleRecordsRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_lifecycle_records_runtime_conformance<
    S: crate::model::LifecycleRecordsRuntime + ?Sized,
>(
    seam: &S,
) {
    // vector: canonical-json-sorts-keys-and-compacts
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
{
  "b": [
    2,
    1
  ],
  "a": "é"
}
"####,
        )
        .expect("value parses");
        let actual = seam.canonical_json(&value);
        let actual_value = serde_json::to_value(actual)
            .expect("canonical-json-sorts-keys-and-compacts: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"{\"a\":\"é\",\"b\":[2,1]}"
"####,
        )
        .expect("canonical-json-sorts-keys-and-compacts: expected parses");
        assert_eq!(
            actual_value, expected,
            "canonical-json-sorts-keys-and-compacts misrouted"
        );
    }
    // vector: check-public-accepts-placeholders
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
{
  "apiKey": "[redacted]",
  "nested": {
    "password": "<redacted>"
  }
}
"####,
        )
        .expect("value parses");
        let actual = seam.check_public(&value);
        let actual_value =
            serde_json::to_value(actual).expect("check-public-accepts-placeholders: serialize");
        let expected: Value = serde_json::from_str(
            r####"
true
"####,
        )
        .expect("check-public-accepts-placeholders: expected parses");
        assert_eq!(
            actual_value, expected,
            "check-public-accepts-placeholders misrouted"
        );
    }
    // skipped: check-public-rejects-camelcase-secret-key — expectedError on a @sync op has no typed error channel
    // skipped: check-public-rejects-credential-value — expectedError on a @sync op has no typed error channel
    // skipped: check-public-rejects-nested-assignment-string — expectedError on a @sync op has no typed error channel
    // skipped: check-public-rejects-secret-key — expectedError on a @sync op has no typed error channel
    // vector: content-hash-canonical-object
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
{
  "b": [
    2,
    1
  ],
  "a": "é"
}
"####,
        )
        .expect("value parses");
        let actual = seam.content_hash(&value);
        let actual_value =
            serde_json::to_value(actual).expect("content-hash-canonical-object: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"265cdd44ca612f13fd2b8e14f6913a5513adf3142e6c82317e55ba51948f43f2"
"####,
        )
        .expect("content-hash-canonical-object: expected parses");
        assert_eq!(
            actual_value, expected,
            "content-hash-canonical-object misrouted"
        );
    }
    // vector: content-hash-example-input
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
{
  "input": "question-0"
}
"####,
        )
        .expect("value parses");
        let actual = seam.content_hash(&value);
        let actual_value =
            serde_json::to_value(actual).expect("content-hash-example-input: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"d3d9fa86e6735affbb18ca08a7306a6fe3cd8f6b335422e44ef85591d5b7ddb1"
"####,
        )
        .expect("content-hash-example-input: expected parses");
        assert_eq!(
            actual_value, expected,
            "content-hash-example-input misrouted"
        );
    }
    // vector: example-id-hashes-input-only
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
{
  "input": "question-0",
  "reference": "reference-0",
  "group": "conversation-0",
  "provenance": [
    "trace-0"
  ],
  "reviewers": [
    "human-reviewer"
  ],
  "referenceOrigins": [
    "human"
  ]
}
"####,
        )
        .expect("value parses");
        let actual = seam.example_id(&value);
        let actual_value =
            serde_json::to_value(actual).expect("example-id-hashes-input-only: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"d3d9fa86e6735affbb18ca08a7306a6fe3cd8f6b335422e44ef85591d5b7ddb1"
"####,
        )
        .expect("example-id-hashes-input-only: expected parses");
        assert_eq!(
            actual_value, expected,
            "example-id-hashes-input-only misrouted"
        );
    }
    // vector: record-id-agent-hash-vector
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
{
  "schemaVersion": 1,
  "kind": "agent",
  "sourceFiles": [
    {
      "path": "agent.py",
      "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      "size": 0
    }
  ],
  "dependencies": {},
  "model": {
    "deployment": "baseline"
  },
  "instructions": "Be helpful.",
  "tools": []
}
"####,
        )
        .expect("value parses");
        let actual = seam.record_id(&value);
        let actual_value =
            serde_json::to_value(actual).expect("record-id-agent-hash-vector: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"1adec8c6672ca08db9323fe9512150565047d77d3df71b71c6a2a7932b4346da"
"####,
        )
        .expect("record-id-agent-hash-vector: expected parses");
        assert_eq!(
            actual_value, expected,
            "record-id-agent-hash-vector misrouted"
        );
    }
    // vector: safe-path-normalizes-backslashes
    {
        let path: String = serde_json::from_str(
            r####"
"src\\main.py"
"####,
        )
        .expect("path parses");
        let actual = seam.safe_path(&path);
        let actual_value =
            serde_json::to_value(actual).expect("safe-path-normalizes-backslashes: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"src/main.py"
"####,
        )
        .expect("safe-path-normalizes-backslashes: expected parses");
        assert_eq!(
            actual_value, expected,
            "safe-path-normalizes-backslashes misrouted"
        );
    }
    // skipped: safe-path-rejects-empty — expectedError on a @sync op has no typed error channel
    // skipped: safe-path-rejects-traversal — expectedError on a @sync op has no typed error channel
    // skipped: safe-path-rejects-windows-device — expectedError on a @sync op has no typed error channel
}

/// Typed @vector conformance for LifecycleStorageRuntime. Pass your real `impl LifecycleStorageRuntime`; the
/// `S: LifecycleStorageRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_lifecycle_storage_runtime_conformance(&LifecycleStorageRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_lifecycle_storage_runtime_conformance<
    S: crate::model::LifecycleStorageRuntime + ?Sized,
>(
    seam: &S,
) {
    // vector: put-artifact-is-idempotent
    {
        let root: String = serde_json::from_str(
            r####"
"$temp/evidence"
"####,
        )
        .expect("root parses");
        let record: serde_json::Value = serde_json::from_str(
            r####"
{
  "schemaVersion": 1,
  "kind": "agent",
  "sourceFiles": [],
  "dependencies": {},
  "model": {
    "deployment": "baseline"
  },
  "instructions": "Be helpful."
}
"####,
        )
        .expect("record parses");
        let actual = seam.put_artifact(&root, &record);
        let actual_value =
            serde_json::to_value(actual).expect("put-artifact-is-idempotent: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"c495bdfc9ddaea5fae01f5e8363543acb8fe64306767df0330856c14bc3c6d59"
"####,
        )
        .expect("put-artifact-is-idempotent: expected parses");
        assert_eq!(
            actual_value, expected,
            "put-artifact-is-idempotent misrouted"
        );
    }
    // vector: put-artifact-writes-normalized-envelope
    {
        let root: String = serde_json::from_str(
            r####"
"$temp/evidence"
"####,
        )
        .expect("root parses");
        let record: serde_json::Value = serde_json::from_str(
            r####"
{
  "schemaVersion": 1,
  "kind": "agent",
  "sourceFiles": [],
  "dependencies": {},
  "model": {
    "deployment": "baseline"
  },
  "instructions": "Be helpful."
}
"####,
        )
        .expect("record parses");
        let actual = seam.put_artifact(&root, &record);
        let actual_value = serde_json::to_value(actual)
            .expect("put-artifact-writes-normalized-envelope: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"c495bdfc9ddaea5fae01f5e8363543acb8fe64306767df0330856c14bc3c6d59"
"####,
        )
        .expect("put-artifact-writes-normalized-envelope: expected parses");
        assert_eq!(
            actual_value, expected,
            "put-artifact-writes-normalized-envelope misrouted"
        );
    }
}

/// Typed @vector conformance for ResponsesRuntime. Pass your real `impl ResponsesRuntime`; the
/// `S: ResponsesRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_responses_runtime_conformance(&ResponsesRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_responses_runtime_conformance<S: crate::model::ResponsesRuntime + ?Sized>(seam: &S) {
    // vector: bare-string-items-fall-back-to-last
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
[
  "first",
  "second"
]
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value =
            serde_json::to_value(actual).expect("bare-string-items-fall-back-to-last: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"second"
"####,
        )
        .expect("bare-string-items-fall-back-to-last: expected parses");
        assert_eq!(
            actual_value, expected,
            "bare-string-items-fall-back-to-last misrouted"
        );
    }
    // vector: empty-list-is-empty
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
[]
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("empty-list-is-empty: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("empty-list-is-empty: expected parses");
        assert_eq!(actual_value, expected, "empty-list-is-empty misrouted");
    }
    // vector: empty-string
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("empty-string: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("empty-string: expected parses");
        assert_eq!(actual_value, expected, "empty-string misrouted");
    }
    // vector: list-content-parts
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
[
  {
    "role": "user",
    "content": [
      {
        "type": "input_text",
        "text": "part one "
      },
      {
        "type": "input_text",
        "text": "part two"
      }
    ]
  }
]
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("list-content-parts: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"part one part two"
"####,
        )
        .expect("list-content-parts: expected parses");
        assert_eq!(actual_value, expected, "list-content-parts misrouted");
    }
    // vector: list-role-string-content
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
[
  {
    "role": "user",
    "content": "say hi"
  }
]
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value =
            serde_json::to_value(actual).expect("list-role-string-content: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"say hi"
"####,
        )
        .expect("list-role-string-content: expected parses");
        assert_eq!(actual_value, expected, "list-role-string-content misrouted");
    }
    // vector: non-list-non-string-is-empty
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
{
  "role": "user"
}
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value =
            serde_json::to_value(actual).expect("non-list-non-string-is-empty: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("non-list-non-string-is-empty: expected parses");
        assert_eq!(
            actual_value, expected,
            "non-list-non-string-is-empty misrouted"
        );
    }
    // vector: null-is-empty
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
{}
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("null-is-empty: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("null-is-empty: expected parses");
        assert_eq!(actual_value, expected, "null-is-empty misrouted");
    }
    // vector: number-is-empty
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
42
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("number-is-empty: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("number-is-empty: expected parses");
        assert_eq!(actual_value, expected, "number-is-empty misrouted");
    }
    // vector: output-text-and-text-part-types
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
[
  {
    "role": "user",
    "content": [
      {
        "type": "output_text",
        "text": "a"
      },
      {
        "type": "text",
        "text": "b"
      }
    ]
  }
]
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value =
            serde_json::to_value(actual).expect("output-text-and-text-part-types: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"ab"
"####,
        )
        .expect("output-text-and-text-part-types: expected parses");
        assert_eq!(
            actual_value, expected,
            "output-text-and-text-part-types misrouted"
        );
    }
    // vector: plain-string
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
"hello world"
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("plain-string: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"hello world"
"####,
        )
        .expect("plain-string: expected parses");
        assert_eq!(actual_value, expected, "plain-string misrouted");
    }
    // vector: prefers-last-user-turn
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
[
  {
    "role": "user",
    "content": "first"
  },
  {
    "role": "assistant",
    "content": "reply"
  },
  {
    "role": "user",
    "content": "second"
  }
]
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual).expect("prefers-last-user-turn: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"second"
"####,
        )
        .expect("prefers-last-user-turn: expected parses");
        assert_eq!(actual_value, expected, "prefers-last-user-turn misrouted");
    }
    // vector: roleless-item-falls-back
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
[
  {
    "content": "no role here"
  }
]
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value =
            serde_json::to_value(actual).expect("roleless-item-falls-back: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"no role here"
"####,
        )
        .expect("roleless-item-falls-back: expected parses");
        assert_eq!(actual_value, expected, "roleless-item-falls-back misrouted");
    }
    // vector: user-turn-wins-over-later-roleless-without-text
    {
        let value: serde_json::Value = serde_json::from_str(
            r####"
[
  {
    "role": "user",
    "content": "the question"
  },
  {
    "role": "assistant",
    "content": ""
  }
]
"####,
        )
        .expect("value parses");
        let actual = seam.input_text(&value);
        let actual_value = serde_json::to_value(actual)
            .expect("user-turn-wins-over-later-roleless-without-text: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"the question"
"####,
        )
        .expect("user-turn-wins-over-later-roleless-without-text: expected parses");
        assert_eq!(
            actual_value, expected,
            "user-turn-wins-over-later-roleless-without-text misrouted"
        );
    }
}

/// Typed @vector conformance for RoutingRuntime. Pass your real `impl RoutingRuntime`; the
/// `S: RoutingRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_routing_runtime_conformance(&RoutingRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_routing_runtime_conformance<S: crate::model::RoutingRuntime + ?Sized>(seam: &S) {
    let ctx = crate::model::context::LoadContext::default();
    // vector: direct-rejects-non-teams
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "type": "message",
  "channelId": "slack",
  "conversation": {
    "conversationType": "personal"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.teams_direct_message(&activity);
        let actual_value =
            serde_json::to_value(actual).expect("direct-rejects-non-teams: serialize");
        let expected: Value = serde_json::from_str(
            r####"
false
"####,
        )
        .expect("direct-rejects-non-teams: expected parses");
        assert_eq!(actual_value, expected, "direct-rejects-non-teams misrouted");
    }
    // vector: teams-channel-mention
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "type": "message",
  "channelId": "msteams",
  "conversation": {
    "conversationType": "channel"
  },
  "recipient": {
    "id": "28:agent"
  },
  "entities": [
    {
      "type": "mention",
      "mentioned": {
        "id": "28:agent"
      },
      "text": "<at>HAL</at>"
    }
  ]
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.teams_tagged_channel_message(&activity);
        let actual_value = serde_json::to_value(actual).expect("teams-channel-mention: serialize");
        let expected: Value = serde_json::from_str(
            r####"
true
"####,
        )
        .expect("teams-channel-mention: expected parses");
        assert_eq!(actual_value, expected, "teams-channel-mention misrouted");
    }
    // vector: teams-channel-without-mention
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "type": "message",
  "channelId": "msteams",
  "conversation": {
    "conversationType": "channel"
  },
  "recipient": {
    "id": "28:agent"
  },
  "entities": [
    {
      "type": "mention",
      "mentioned": {
        "id": "29:user"
      },
      "text": "<at>User</at>"
    }
  ]
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.teams_tagged_channel_message(&activity);
        let actual_value =
            serde_json::to_value(actual).expect("teams-channel-without-mention: serialize");
        let expected: Value = serde_json::from_str(
            r####"
false
"####,
        )
        .expect("teams-channel-without-mention: expected parses");
        assert_eq!(
            actual_value, expected,
            "teams-channel-without-mention misrouted"
        );
    }
    // vector: teams-direct
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "type": "message",
  "channelId": "msteams",
  "conversation": {
    "conversationType": "personal"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.teams_direct_message(&activity);
        let actual_value = serde_json::to_value(actual).expect("teams-direct: serialize");
        let expected: Value = serde_json::from_str(
            r####"
true
"####,
        )
        .expect("teams-direct: expected parses");
        assert_eq!(actual_value, expected, "teams-direct misrouted");
    }
    // vector: teams-direct-channel-suffix
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "type": "message",
  "channelId": "msteams:tenant",
  "conversation": {
    "conversationType": "personal"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.teams_direct_message(&activity);
        let actual_value =
            serde_json::to_value(actual).expect("teams-direct-channel-suffix: serialize");
        let expected: Value = serde_json::from_str(
            r####"
true
"####,
        )
        .expect("teams-direct-channel-suffix: expected parses");
        assert_eq!(
            actual_value, expected,
            "teams-direct-channel-suffix misrouted"
        );
    }
    // vector: teams-group
    {
        let activity = crate::model::Activity::from_json(
            r####"
{
  "type": "message",
  "channelId": "msteams",
  "conversation": {
    "conversationType": "groupChat"
  }
}
"####,
            &ctx,
        )
        .expect("activity parses");
        let actual = seam.teams_group_chat_message(&activity);
        let actual_value = serde_json::to_value(actual).expect("teams-group: serialize");
        let expected: Value = serde_json::from_str(
            r####"
true
"####,
        )
        .expect("teams-group: expected parses");
        assert_eq!(actual_value, expected, "teams-group misrouted");
    }
}

/// Typed @vector conformance for RuntimeDispatchRuntime. Pass your real `impl RuntimeDispatchRuntime`; the
/// `S: RuntimeDispatchRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_runtime_dispatch_runtime_conformance(&RuntimeDispatchRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_runtime_dispatch_runtime_conformance<
    S: crate::model::RuntimeDispatchRuntime + ?Sized,
>(
    seam: &S,
) {
    // vector: activity-result-empty-or-non-string-is-none
    {
        let result: serde_json::Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("result parses");
        let actual = seam.activity_result_text(&result);
        let actual_value = serde_json::to_value(actual)
            .expect("activity-result-empty-or-non-string-is-none: serialize");
        let expected: Value = serde_json::from_str(
            r####"
null
"####,
        )
        .expect("activity-result-empty-or-non-string-is-none: expected parses");
        assert_eq!(
            actual_value, expected,
            "activity-result-empty-or-non-string-is-none misrouted"
        );
    }
    // vector: activity-result-non-string-is-none
    {
        let result: serde_json::Value = serde_json::from_str(
            r####"
42
"####,
        )
        .expect("result parses");
        let actual = seam.activity_result_text(&result);
        let actual_value =
            serde_json::to_value(actual).expect("activity-result-non-string-is-none: serialize");
        let expected: Value = serde_json::from_str(
            r####"
null
"####,
        )
        .expect("activity-result-non-string-is-none: expected parses");
        assert_eq!(
            actual_value, expected,
            "activity-result-non-string-is-none misrouted"
        );
    }
    // vector: activity-result-nonempty-string
    {
        let result: serde_json::Value = serde_json::from_str(
            r####"
"ok"
"####,
        )
        .expect("result parses");
        let actual = seam.activity_result_text(&result);
        let actual_value =
            serde_json::to_value(actual).expect("activity-result-nonempty-string: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"ok"
"####,
        )
        .expect("activity-result-nonempty-string: expected parses");
        assert_eq!(
            actual_value, expected,
            "activity-result-nonempty-string misrouted"
        );
    }
    // vector: stream-chunks-empty-string-is-empty
    {
        let result: serde_json::Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("result parses");
        let actual = seam.stream_chunks(&result);
        let actual_value =
            serde_json::to_value(actual).expect("stream-chunks-empty-string-is-empty: serialize");
        let expected: Value = serde_json::from_str(
            r####"
[]
"####,
        )
        .expect("stream-chunks-empty-string-is-empty: expected parses");
        assert_eq!(
            actual_value, expected,
            "stream-chunks-empty-string-is-empty misrouted"
        );
    }
    // vector: stream-chunks-filter-empty-and-non-string
    {
        let result: serde_json::Value = serde_json::from_str(
            r####"
[
  "a",
  "",
  1,
  "b"
]
"####,
        )
        .expect("result parses");
        let actual = seam.stream_chunks(&result);
        let actual_value = serde_json::to_value(actual)
            .expect("stream-chunks-filter-empty-and-non-string: serialize");
        let expected: Value = serde_json::from_str(
            r####"
[
  "a",
  "b"
]
"####,
        )
        .expect("stream-chunks-filter-empty-and-non-string: expected parses");
        assert_eq!(
            actual_value, expected,
            "stream-chunks-filter-empty-and-non-string misrouted"
        );
    }
    // vector: stream-chunks-non-stream-result-is-empty
    {
        let result: serde_json::Value = serde_json::from_str(
            r####"
42
"####,
        )
        .expect("result parses");
        let actual = seam.stream_chunks(&result);
        let actual_value = serde_json::to_value(actual)
            .expect("stream-chunks-non-stream-result-is-empty: serialize");
        let expected: Value = serde_json::from_str(
            r####"
[]
"####,
        )
        .expect("stream-chunks-non-stream-result-is-empty: expected parses");
        assert_eq!(
            actual_value, expected,
            "stream-chunks-non-stream-result-is-empty misrouted"
        );
    }
    // vector: stream-chunks-single-string
    {
        let result: serde_json::Value = serde_json::from_str(
            r####"
"done"
"####,
        )
        .expect("result parses");
        let actual = seam.stream_chunks(&result);
        let actual_value =
            serde_json::to_value(actual).expect("stream-chunks-single-string: serialize");
        let expected: Value = serde_json::from_str(
            r####"
[
  "done"
]
"####,
        )
        .expect("stream-chunks-single-string: expected parses");
        assert_eq!(
            actual_value, expected,
            "stream-chunks-single-string misrouted"
        );
    }
    // vector: wire-return-body-string-or-empty
    {
        let result: serde_json::Value = serde_json::from_str(
            r####"
42
"####,
        )
        .expect("result parses");
        let actual = seam.return_body(&result);
        let actual_value =
            serde_json::to_value(actual).expect("wire-return-body-string-or-empty: serialize");
        let expected: Value = serde_json::from_str(
            r####"
""
"####,
        )
        .expect("wire-return-body-string-or-empty: expected parses");
        assert_eq!(
            actual_value, expected,
            "wire-return-body-string-or-empty misrouted"
        );
    }
    // vector: wire-return-body-string-passthrough
    {
        let result: serde_json::Value = serde_json::from_str(
            r####"
"body"
"####,
        )
        .expect("result parses");
        let actual = seam.return_body(&result);
        let actual_value =
            serde_json::to_value(actual).expect("wire-return-body-string-passthrough: serialize");
        let expected: Value = serde_json::from_str(
            r####"
"body"
"####,
        )
        .expect("wire-return-body-string-passthrough: expected parses");
        assert_eq!(
            actual_value, expected,
            "wire-return-body-string-passthrough misrouted"
        );
    }
}

/// Typed @vector conformance for RuntimeRouterRuntime. Pass your real `impl RuntimeRouterRuntime`; the
/// `S: RuntimeRouterRuntime` bound makes the compiler prove every op is implemented. Call
/// from a test, e.g. `run_runtime_router_runtime_conformance(&RuntimeRouterRuntimeImpl).await;` (or without `.await` when sync).
pub fn run_runtime_router_runtime_conformance<S: crate::model::RuntimeRouterRuntime + ?Sized>(
    seam: &S,
) {
    // vector: registered-protocols-activity-first-wire-order
    {
        let activity_route_count: i32 = serde_json::from_str(
            r####"
1
"####,
        )
        .expect("activityRouteCount parses");
        let invoke_names: Vec<String> = serde_json::from_str(
            r####"
[]
"####,
        )
        .expect("invokeNames parses");
        let wire_protocols: Vec<String> = serde_json::from_str(
            r####"
[
  "chat",
  "responses"
]
"####,
        )
        .expect("wireProtocols parses");
        let actual =
            seam.registered_protocols(&activity_route_count, &invoke_names, &wire_protocols);
        let actual_value = serde_json::to_value(actual)
            .expect("registered-protocols-activity-first-wire-order: serialize");
        let expected: Value = serde_json::from_str(
            r####"
[
  "activity",
  "responses",
  "chat"
]
"####,
        )
        .expect("registered-protocols-activity-first-wire-order: expected parses");
        assert_eq!(
            actual_value, expected,
            "registered-protocols-activity-first-wire-order misrouted"
        );
    }
    // vector: registered-protocols-invoke-only-is-activity
    {
        let activity_route_count: i32 = serde_json::from_str(
            r####"
0
"####,
        )
        .expect("activityRouteCount parses");
        let invoke_names: Vec<String> = serde_json::from_str(
            r####"
[
  "message/submitAction"
]
"####,
        )
        .expect("invokeNames parses");
        let wire_protocols: Vec<String> = serde_json::from_str(
            r####"
[]
"####,
        )
        .expect("wireProtocols parses");
        let actual =
            seam.registered_protocols(&activity_route_count, &invoke_names, &wire_protocols);
        let actual_value = serde_json::to_value(actual)
            .expect("registered-protocols-invoke-only-is-activity: serialize");
        let expected: Value = serde_json::from_str(
            r####"
[
  "activity"
]
"####,
        )
        .expect("registered-protocols-invoke-only-is-activity: expected parses");
        assert_eq!(
            actual_value, expected,
            "registered-protocols-invoke-only-is-activity misrouted"
        );
    }
    // vector: registered-protocols-no-chat-publishable-assumption
    {
        let activity_route_count: i32 = serde_json::from_str(
            r####"
0
"####,
        )
        .expect("activityRouteCount parses");
        let invoke_names: Vec<String> = serde_json::from_str(
            r####"
[]
"####,
        )
        .expect("invokeNames parses");
        let wire_protocols: Vec<String> = serde_json::from_str(
            r####"
[
  "chat",
  "invocations",
  "responses_stream",
  "responses"
]
"####,
        )
        .expect("wireProtocols parses");
        let actual =
            seam.registered_protocols(&activity_route_count, &invoke_names, &wire_protocols);
        let actual_value = serde_json::to_value(actual)
            .expect("registered-protocols-no-chat-publishable-assumption: serialize");
        let expected: Value = serde_json::from_str(
            r####"
[
  "responses",
  "invocations",
  "chat"
]
"####,
        )
        .expect("registered-protocols-no-chat-publishable-assumption: expected parses");
        assert_eq!(
            actual_value, expected,
            "registered-protocols-no-chat-publishable-assumption misrouted"
        );
    }
}
